### ISSUE TITLE
Race condition between cache and policy

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#137]
There is a race condition between cache and policy, which will cause policy schedule more pods on the same host. Here are the details:

##### T1. Cache thread:
  
  1. Update Pod/Node/Consumer information from api-server

##### T2.Policy - resource alloc thread:
  
  1. Get Pod/Node/Consumer snapshot from Cache
  2. Allocate resources for Pod/PodSet in the cache snapshot
    2.1. Assign MinAvailable to each PodSet one by one
    2.2. Assign left resources to each PodSet by DRF
  3. Add allocate resources result to a queue, name it as `AllocationQueue`

##### T3.Policy - process alloc decision thread:
  
  1. Get the scheduler result from `AllocationQueue` and update it into api-server

##### T4.Kubelet
  
  1. Get Pod information from api-server, start/stop it and then update status to api-server

### Case 01:
1. In step T2.2.1: Policy allocate MinAvailable to PodSet
2. In step T2.3: Policy add allocate result to `AllocationQueue`  (Pods still pending)
3. In step T3.1: Policy update allocate result to api-server (Pods still pending, with Nodename)
4. In step T1.1: Cache update information from api-server in step T1.1 (Pods still pending, with Nodename)
5. In step T2.1: Policy get cache snapshot (Pods still pending, with Nodename)
6. In step T2.2.1: Policy allocate MinAvailable to PodSet, however, the policy doesn't calculate the number of pending pods with Nodename, still get pods from pending queue one by one.
7. In step T3.1: Policy update allocate result to api-server (more Pods still pending, with Nodename)
8. In step T4.1: Kubelet start pods

### Case 02:
1. In step T2.2.1: Policy allocate MinAvailable to PodSet 
2. In step T2.3: Policy add allocate result to `AllocationQueue` (Pods still pending)
3. In step T3.1: Policy update allocate result to api-server (Pods still pending, with Nodename)
4. In step T2.1: Policy get cache snapshot (Pods still pending)
5. In step T1.1: Cache update information from api-server (Pods still pending, with Nodename)
6. In step T2.2.1: Policy allocate MinAvailable to PodSet, however, all the pods in the pending queue without nodename, it may cause policy allocate more MinAvailable in this step.
7. In step T3.1: Policy update allocate result to api-server (more Pods still pending, with Nodename)
8. In step T4.1: Kubelet start pods

**Comment by k82cn** [comment]
For this case, is it possible to assume the pod in cache before binding? please refer to kube-scheduler for it.

**Comment by jinzhejz** [comment]
This issue is fixed by PR #154 , close it.
