### ISSUE TITLE
Support GPU for ML/AI framework

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#145]

**Comment by vditya** [comment]
@k82cn We (Nvidia) have also started to look at kuber-arbitrator for our internal use of deploying GPU batch jobs over multiple tenant environment. It will be good to contribute together on this. Have you already started work on this?

**Comment by k82cn** [comment]
@vditya , that'll be great if we can work together for this :). I'm learning the related features in upstream, the work does not start yet.

**Comment by seyong-um** [comment]
I am also interested in this. I hope we contribute together

**Comment by k82cn** [comment]
@vditya @ssseyong , that'll be great if there's someone can draft a design doc for that :)

**Comment by k82cn** [comment]
Duplicated with #236 ; I'll continue the work at #236 :)
