### ISSUE TITLE
Consider relationship between QueueJob and Application

### ISSUE THREAD

**Issue by davidopp** [kubernetes-retired/kube-batch#150]
I noticed today the proposal for an [Application API object](https://github.com/kubernetes/community/pull/1629) which, at first glance, appears to be a way to group multiple API objects needed to launch an application. This seems pretty similar to the QueueJob concept from the original kube arbitrator proposal, at least at a high level (in particular see the `ApplicationSpec.Components` field). Anyway, I just wanted to point this out so you might look into whether there is anything to leverage from `Application.` Maybe there is not a useful connection, but it is probably worth investigating.

**Comment by k82cn** [comment]
Thanks very much for the info! I'll take some to learn it :)

**Comment by k82cn** [comment]
After went through the proposal of `Application` Kind, I'd like to make `QueueJob` as sub kind of it: the `QueueJob` only provide the capability for batch job, e.g.  MP,. and use Application to manage dependency, e.g. Spark master and executor.

/cc @bsalamat

**Comment by k82cn** [comment]
/remove-lifecycle stale

We may do integration with `Application` later when `QueueJob` is ready.
