### ISSUE TITLE
[question] The relationship between quotalloc and batchd

### ISSUE THREAD

**Issue by gaocegege** [kubernetes-retired/kube-batch#156]
Hi, kube-arbitrator members

I am trying to run ML(especially TF) workload on Kubernetes with the support of kube-arbitrator, and have some questions about this repo.

First, what's the relationship between kube-arbitrator and [IBM EGO](https://www.ibm.com/developerworks/cn/analytics/library/ba-cn-ego-intro-whitepaper/index.html), is it an open source re-implementation of EGO? And if I'm not mistaken I think EGO is similar to mesos:

> EGO 还在其内核中提供了一个高度可配置的、高效的中央布局服务

I was wondering what is a `中央布局服务`, I can not find the description in the post.

Second, what's the relationship between batchd and quotalloc? I found that they have a similar CRD: `QuotaAllocator` and `Queue`, but I am not sure what is it used to do.

Finally, I have a question about the behavioud of batchd:

> When resources are not sufficient, Kube-batchd just tries to start minAvailable pods of each application as much as possible.

If I have two applications: the first one `app1`'s minAvailable pod is 4, and the second one `app2`'s minAvailable pod is 6. There are only 5 slots in the machine, then what will happen if batched schedules the two applications?

I'd appreciate it if you could help me 😄

**Comment by jinzhejz** [comment]
* About the second question:

For TF workload, I think you can use `kube-batchd`. It is to schedule batch jobs. The CRD `Queue` is like a job set, it contains multiple jobs, `kube-batchd` will schedule all jobs cross `Queue`. Currently, `Queue` can be created by `kube-batchd` automatically. You just need to submit your jobs. Refer to [batchd_tutorial](https://github.com/kubernetes-incubator/kube-arbitrator/blob/master/doc/usage/batchd_tutorial.md) for `kube-batchd` usage.

`kube-quotalloc` is still under discussion, it can be ignored temporarily. Related documents will be updated after the discussion is done.

* About your case:

Now `kube-batchd` will the sort the two applications by their owner(which is assigned by kubernetes) first. And then schedule minAvailable pods for the two applications one by one. So there may be two results(it depends on what are their owners):

1. `app1` get 4 slots, `app2` get 1 slots
2. `app2` get 5 slots, `app1` get 0 slots

In this case, I think the first result is preferred, right? If yes, we can trace it as an issue.

**Comment by gaocegege** [comment]
@jinzhejz Thanks for your comment.

In the case, It depends on the applications. I know the behaviour of the batched and thanks.

There is one feature that I think our workload may need. 

We can take a TF job as an example, which contains two parameter server(key value store), one chief worker(master worker, which must be up), two stateless workers. And at least the PS and the chief worker is up, the TFJob is considered to be working. But we can not set the minAvailable to be 3, since we do not know which one is chief, all of the pods have the same labels. 

The pods in one application have different roles, then I think only `minAvailable` is not enough. Some important pods should be in minAvailable and other maybe not, so label-based solution may be better, IMO.

And, I was wondering why the `app2` could get 5 slots in the case. Its `minAvailable` is 6, if we give the application 5 slots it still can not work.

**Comment by jinzhejz** [comment]
@gaocegege 

In your TF job(two PS pods, one chief worker pod, two stateless worker pods), I think we could specify a different priority for these pods. PS pod has the highest priority. Chief worker pod has second highest priority. Stateless worker pod has the lowest priority. And `minAvailable` is 3 for this job.

When `kube-batchd` start `minAvailable` pods for the job, it could start the pods based on their priority. PS pods start first, and then chief worker pod, then stateless worker pod.

The pod priority could not cross jobs, only works in a job. And I think this pod priority way may be enough for a tensorflow job.

About `app2` could get 5 slots, because the cluster resources are not sufficient(`app2`'s minAvailable is 6, the cluster slots are 5), `kube-batchd` just tries to meet its minAvailable as much as possible. 
`kube-batchd` is going to support that it will not assign any resources to the job unless its `minAvailable` could be met.

**Comment by gaocegege** [comment]
@jinzhejz 

Thanks for your explanation, I will have a try on it.

> kube-batchd is going to support that it will not assign any resources to the job unless its minAvailable could be met.

This is awesome 😄

**Comment by jinzhejz** [comment]
@gaocegege 

The pod priority is not implemented yet, issue #159 is logged to trace it :)

**Comment by gaocegege** [comment]
@jinzhejz Thank you and I am going to close the issue :)
