### ISSUE TITLE
Schedule pods by priority for minAvailable

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#159]
Currently, `kube-batchd` assign pod of job randomly for `minAvailable`. 

For example, there are three pods `p1` `p2` `p3` in a job, and its `minAvailable` is 2. `kube-batchd` may start `minAvailable` pods in three ways

* `p1` and `p2`
* `p1` and `p3`
* `p2` and `p3`

for some job, such as tensorflow job, some pods of the job must start first. Otherwise, the job could not startup.

To handle above issue, the user could specify a different priority for pods, then `kube-batchd` will start `minAvailable` pods for the job based on their priority.

**Comment by k82cn** [comment]
xref https://github.com/kubeflow/tf-operator/issues/349

**Comment by gaocegege** [comment]
Is it implemented based on DRF policy?

**Comment by k82cn** [comment]
yes, based on DRF; if work together with gang scheduling, no DRF.

**Comment by gaocegege** [comment]
Thanks for your reply @k82cn 

I will keep an eye on it 😄

**Comment by k82cn** [comment]
Done :)
