### ISSUE TITLE
Race condition between cache and policy

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#161]
`kube-batchd` reuse kubernetes PDB for `minAvailable`. Scheduler cache sync PDB from api-server and policy get cache snapshot for scheduling.

While the policy may get cache snapshot before cache sync PDB from api-server. It may cause policy lost `minAvailable` of a PodSet when scheduling pods for it.

**Comment by k82cn** [comment]
Currently, the kar-scheduler will not schedule the PodSet/Job if did not get `PDB`/`SchedulingSpec`. I'd like to make `PDB`/`SchedulingSpec` required.
