### ISSUE TITLE
Add node selector to identify a sub-cluster for batch job

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#164]
Currently, we cached all node in `kube-bached` and assign node to pod accordingly. But for batch job, the conflict is so heavy :(. We'll use 'static' zone for batch job before finding a "good" way to work together with kube-scheduler.

List some tasks (including but not limited to)
- [x] Filter pods with scheduler name for `kube-batchd` (#170)
- [x] Filter nodes with labels for `kube-batchd` (#203)
- [ ] Filter nodes with NodeAffinity for `kube-batchd`

**Comment by sedflix** [comment]
@k82cn No one is working on it, right?

@k82cn @jinzhejz 
Is this the requirement? "Nodes, having a particular label X, will be considered by kube-batchd"

**Comment by k82cn** [comment]
The feature was done; close this.
