### ISSUE TITLE
[Request] Publish scheduler events to pod

### ISSUE THREAD

**Issue by gaocegege** [kubernetes-retired/kube-batch#172]
The default scheduler publishes events to pod:

```
  FirstSeen	LastSeen	Count	From			SubObjectPath				Type		Reason		Message
  ---------	--------	-----	----			-------------				--------	------		-------
  17m		17m		1	default-scheduler						Normal		ScheduledSuccessfully assigned kube-batchd-5f86bd5b6-hx8kt to ist
```

But batchd does not implement it, it seems that batchd does not have the recorder. I think it should be added to make users know which scheduler schedules the pod.

**Comment by k82cn** [comment]
hmm... Maybe we can publish event in 'Job' level :). For some batch workload, there'll be so many tasks (Pods) there.

**Comment by k82cn** [comment]
We already have an event for PodGroup (job level).

```
13s         Warning   unschedulable      PodGroup   not enough valid tasks for gang-scheduling
```
