### ISSUE TITLE
Group pods into one PodSet when they belong to same deployment

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#185]
Currently, `kube-batchd` groups pods into a PodSet by their owner references. However, it will cause some problems in following cases:

**K8S Deployment**
A deployment may contain more than one RS when rolling-upgrade happens, pods in different RS have different owner references, so `kube-batchd` will group them into different PodSet. However, these pods belong to the same deployment and should be in one PodSet.

~~**Kubeflow job**~~
~~In a tfjob, kubeflow create Master/PS/Worker as a k8s job and each job contains one pod. `kube-batchd` will group these pods into different PodSet because of different owner references. However, they belong to the same tfjob and should be in one PodSet.~~

**Comment by k82cn** [comment]
Does tf-operator support this by default? If not , we need to sync up with Kubeflow team for the interface changed.

**Comment by jinzhejz** [comment]
append related details on tf-operator issue [Enable kube-arbitrator as scheduler for tensorflow](https://github.com/kubeflow/tf-operator/issues/349)

**Comment by yanniszark** [comment]
Kubeflow: It seems that in the latest version of tf-operator all pods are owned by the same TfJob, so that part seems to be compatible. (https://github.com/kubeflow/tf-operator/issues/349)

**Comment by jinzhejz** [comment]
@yanniszark yes, this seems not a issue for kubeflow now

**Comment by jinzhejz** [comment]
K8S deployment is long-running service and should be handled by default scheduler. So close this issue directly.
