### ISSUE TITLE
hack/verify-golint.sh: Incorrect check for Go version

### ISSUE THREAD

**Issue by SpandanKumarSahu** [kubernetes-retired/kube-batch#187]
Problem Description:
Upon executing:
`chmod +x hack/verify-golint.sh; ./hack/verify-golint.sh`

I received the following error message:

Detected go version: go version go1.10 linux/amd64.
Kubernetes requires go1.8.3 or greater.
Please install go1.8.3 or later.

!!! Error in ./hack/verify-golint.sh:334
  Error in ./hack/verify-golint.sh:334. 'return 2' exited with status 2
Call stack:
  1: ./hack/verify-golint.sh:334 main(...)
Exiting with status 1

I verified my go version with `go version` which also confirmed:
                go version go1.10 linux/amd64

**Comment by k82cn** [comment]
Should be handled in #184  :)

**Comment by k82cn** [comment]
fixed by #184 , please try it.
