### ISSUE TITLE
Launch a kube-arbitrator via Kubernetes Deployment/Helm

### ISSUE THREAD

**Issue by rc-zhang** [kubernetes-retired/kube-batch#190]
Hey,

The tutorial here https://github.com/kubernetes-incubator/kube-arbitrator/blob/master/doc/usage/quotalloc_tutorial.md#5-start-kube-quotalloc launch a  kube-quotalloc via downing src code and building, is there any issues about launching kube-quotalloc via Kubernetes Deployment ?

**Comment by k82cn** [comment]
That's a good idea! But we'd better to have a "official" release before publish the image :)

**Comment by k82cn** [comment]
@rc-zhang , currently, we're try to build the docker image for kube-batchd; that'll be great if you can help on that :)

**Comment by k82cn** [comment]
I'd like to make this as part of 0.1 release
