### ISSUE TITLE
build and push kube-batchd/kube-quotalloc images to a public repository?

### ISSUE THREAD

**Issue by rc-zhang** [kubernetes-retired/kube-batch#191]
currently user are required to download src and build kube-batchd/kube-quotalloc.

I am trying to deploy kube-batchd and kube-quotalloc on a minikube cluster. I must ssh into the minkube VM and build kube-batchd/kube-quotalloc form src code and build docker images there. unfortunately, minkube even has no `apt-get`, `make`, `go` installed, building process is a nightmare.

Is it possible to open a public repository on dockerhub ? I am glad to write script to automate the build and push process

**Comment by rc-zhang** [comment]
Oh, I see. kube-batchd/kube-quotalloc need kube-config file and ssh ca/cert to connect API server, currently, user was required to build docker images themself, so they put those files into docker images. If user use pre-build images, they should create related Configmap and Secret.

**Comment by sedflix** [comment]
You don't need to pass kube-config file if you are running kube-batchd/kube-quotalloc inside the cluster.
If kube-config is not specified, it gets to know about the cluster configuration using [InClusterConfig()](https://github.com/kubernetes-incubator/kube-arbitrator/blob/8568559b951bef1b149c262f91fcdae74fddffc8/cmd/kube-batchd/app/server.go#L33). 
Hail `client-go`!

**Comment by k82cn** [comment]
The 0.2 release at https://hub.docker.com/r/kubearbitrator/kube-batchd/
