### ISSUE TITLE
Q: Would having one kube-batchd per namespace work?

### ISSUE THREAD

**Issue by vicaya** [kubernetes-retired/kube-batch#192]
Unlike kube-quotalloc, it looks like that kube-batchd should be able to work in its own namespace isolated from others?

**Comment by k82cn** [comment]
nop, similar to multi-scheduler: one kube-batched and one kube-scheduler are enough for the cluster :) `kube-batched` will use different `schedulerName` from `kube-scheduler`.

**Comment by vicaya** [comment]
I knew that one kube-batchd would work :) My question is that if I deploy kube-batchd (potentially different versions/mods) per namespace with different scheduler names, as long as permission is granted, it should still work, right?

**Comment by k82cn** [comment]
yes. make sure different kube-arbitrator using different scheduler name; and pod uses right scheduler name :)
