### ISSUE TITLE
Allocator with support for queue ordered by priorities of podSets (periodically fetch objects from cache and re-order queue)

### ISSUE THREAD

**Issue by dmatch01** [kubernetes-retired/kube-batch#205]

**Comment by k82cn** [comment]
We need a priority queue for PodSet in drf policy. Currently, we sort PodSet in alphabet order :)

We should now touch too much about the cache, as we need to support customized policy.

**Comment by scostache** [comment]
@k82cn : I thought the code already supports the mentioned feature and it is a matter of adding another allocator plug-in, similar to drf, that maps the priority of the podSet read from their parent to the value used to sort the queue.
