### ISSUE TITLE
Enhanced representation of QJ resources in PolicyController

### ISSUE THREAD

**Issue by dmatch01** [kubernetes-retired/kube-batch#206]
- Currently PolicyController knows about PodSets and schedules one PodSet at a time
- We want to support a group of PodSets (podSets that have the same parent with given priority)

**Comment by k82cn** [comment]
that'll be great to have design doc for this feature :)

**Comment by k82cn** [comment]
btw, please also leverage https://github.com/kubernetes-sigs/application if possible :)
