### ISSUE TITLE
[Question] lack of some basic predicate

### ISSUE THREAD

**Issue by fatkun** [kubernetes-retired/kube-batch#226]
I compare the source between default scheduler and kube-arbitrator, it seems lack of some basic check(such as node not ready, NodeTaints ...) now.If I'm wrong please correct me.

Will these check add to kube-arbitrator in the future?

**Comment by k82cn** [comment]
We'll add those feature on demand :)

**Comment by k82cn** [comment]
I'd like to close this issue; if there's any requirements on any predicates/priorities, please let me know :)
