### ISSUE TITLE
Failed to start kube-batchd

### ISSUE THREAD

**Issue by EdwardZhang88** [kubernetes-retired/kube-batch#229]
I followed the Dockerfile and YAML instructions to install kube-batchd in my cluster. However, I am now stuck with an error below.

Initially, the error was 
`E0531 06:13:09.800011       8 queue_controller.go:70] Fail to create crd Queue, error &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:""}, Status:"Failure", Message:"customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:default\" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope", Reason:"Forbidden", Details:(*v1.StatusDetails)(0xc42039d380), Code:403}}
panic: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kube-system:default" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope`

So I just applied cluster-admin role to kube-system:default by
`kubectl create clusterrolebinding kube-system-default --serviceaccount=kube-system:default --clusterrole=cluster-admin`

This did get me pass the error above but hit another weird error as below.

`kube-batchd-7c94749658-c5rjd               0/1       CrashLoopBackOff  `
`panic: failed to create allocator: &errors.errorString{s:"invalid policy name drf\n"}`

I am not using the docker image from dockerhub. Instead, I compiled the master code and built the image following this [Dockerfile](https://github.com/kubernetes-incubator/kube-arbitrator/blob/master/deployment/Dockerfile) .The only change I made is to change the GPU resource name from nvidia.com/gpu back to alpha.kubernetes.io/nvidia-gpu since our cluster is running the GPU feature gate.

**Comment by k82cn** [comment]
@EdwardZhang88 , the master is unstable right now as we're also do some framework/architect enhancement . If you want to modify the code for your environment, please try this branch: https://github.com/kubernetes-incubator/kube-arbitrator/tree/release-0.1 .

Anyway, I'll also handle this in master ASAP :)

**Comment by k82cn** [comment]
xref https://github.com/kubernetes-incubator/kube-arbitrator/pull/231

**Comment by EdwardZhang88** [comment]
@k8s2n Thanks! After checking out to release-0.1, the kube-batch does work as expected in my cluster when scheduling distributed training pods.
