### ISSUE TITLE
Can kube-batchd co-exist with default scheduler on GPU resource scheduling?

### ISSUE THREAD

**Issue by EdwardZhang88** [kubernetes-retired/kube-batch#235]
@k82cn I have been using both kube-batchd and default scheduler in my cluster and I find that the GPU resources that have already been acclaimed by kube-batchd seem to be still available for scheduling by the default scheduler. 
In my case, I use kube-batchd for distributed training and the default for non distributed. When all GPU are allocated through kube-batchd, I can still submit non-distributed task and the default scheduler will still get the pod scheduled as if there were free GPU. And the pods will end up in a outofalpha.kubernetes.io/nvidia-gpu state, which should have really been Pending for schedule. Is this a known limitation or is there something I miss to configure? Thanks.

**Comment by EdwardZhang88** [comment]
I think I might know what is the cause. Correct me if I am wrong.
So kube-batchd relies on [node status](https://github.com/kubernetes-incubator/kube-arbitrator/blob/master/pkg/batchd/api/node_info.go#L59) to collect the current resource usage
while the default scheduler leverages kubelet and kubelet has maintained a specific [struct](https://github.com/kubernetes/kubernetes/blob/release-1.9/pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go#L60) to record the GPU allocation. Apparently, these two approaches are kind of out of sync, at least, in my environment. When I kubectl get node -o json, the node status will always show there are allocable GPU while all of them have been already used. Have you verified that the node status of GPU is correct for nvidia.com/gpu instead of the legacy 
alpha.kubernetes.io/nvidia-gpu?

**Comment by EdwardZhang88** [comment]
After digging into this problem for a while, I think it's clear now that it's pretty much a scheduler cache thing. Basically, both kube-scheduler and kube-batchd maintain their own scheduler cache. And the resource volume is only updated upon pods addition or removal rather than proactive check of all running/terminating/pending for imagePull pods. This way, whatever usage updated by kube-batched will not be visible to kube-scheduler. I was initially misled by the node.Status.Allocatable  and thought it was meant to be the single source of truce of remaining free resources on the node until I read through [this](https://github.com/kubernetes/kubernetes/blob/160e8d96f6b50b82024d3123f9707d4bcbebecde/pkg/scheduler/cache/node_info.go#L352). And it seems that using two different types of schedulers in the same cluster is simply not encouraged in this [discussion thread](https://github.com/kubernetes/kubernetes/issues/61012). Given that scheduler is designed to be configurable on pod level, I think there has to be a solution to enabling multiple types of schedulers to co-exist.

**Comment by k82cn** [comment]
@EdwardZhang88 , yes, kube-batchd and kube-scheduler maintain scheduler cache in its own process. For two different types of scheduler, kubernetes support [multi-scheduler](https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/); for the decision conflict, one solution is to use node selector to avoid conflict.

Regarding the gang-scheduling in upstream, we're also discussing to move it into kube-arbitrator :)

**Comment by gaocegege** [comment]
Hi, is there any other solution to solve the scheduling conflict? I am not sure if node selector works for us since it is more like a workaround.

**Comment by k82cn** [comment]
>  solve the scheduling conflict

`kubelet` will also check the resource usage of node: if conflict, kubelet will reject the later one. There's do some proposal on smarter layer for multi-scheduler; for now, node selector is straightforward.

**Comment by gaocegege** [comment]
Thanks for your explanation :smile: 

Got it.

**Comment by EdwardZhang88** [comment]
Node selector approach is probably a better way than letting kubelet keep retrying the scheduled yet unfulfilled pods. In our environment, those outofGPUresource pods will cause both unexpected code panic and confusing data as GPU will be shown as over-used in negative numbers. With that being said, I am still interested to find out what are the possible solutions for multi-scheduler. @k82cn Can you share the link regarding 'some proposal on smarter layer for multi-scheduler' if possible? Thanks.

**Comment by k82cn** [comment]
@EdwardZhang88 , please refer to those doc: https://docs.google.com/presentation/d/1DHFhio8p-FRDuyFzlXzOkWn8HAfZlW6SKKrnI50vN0c/edit#slide=id.p15 ; those're only a proposal, we did NOT get any conclusion right now.

**Comment by EdwardZhang88** [comment]
Yeah, thanks for sharing anyway. I will keep an eye on this. Closing this thread for now.
