### ISSUE TITLE
Scheduling GPU resources for deep learning workload based on GPU topology

### ISSUE THREAD

**Issue by suleisl2000** [kubernetes-retired/kube-batch#236]
Expect further GPU support for deep learning training workload. GPU placement is important to deep learning job for better efficiency. 

Same example as described in [YARN-7481](https://issues.apache.org/jira/browse/YARN-7481)
a 2-GPU job runs on gpu {0,1} could be faster than run on gpu {0, 7}, if GPU 0 and 1 are under the same PCI-E switch while 0 and 7 are not.

We expect kube-arbitrator can also support this kind of fine-grained GPU placement.

**Comment by k82cn** [comment]
@suleisl2000 , yes, that feature seems interesting but how about the priority to you?

**Comment by suleisl2000** [comment]
@k82cn [TuSimple](http://tusimple.ai) would like to use kube-arbitrator gang-scheduling in our deep learning hybrid cloud for distributed training, but it doesn’t support GPU topology aware scheduling at present. This feature can benefit to our training workload and it is high priority to us.

**Comment by suleisl2000** [comment]
@hpejustin Firmament is an interesting project and I knew it about two years ago. It is great if we can work on some interesting things and it is better if we can have a chat offline.

**Comment by OyutianO** [comment]
It's need gpu-device-plugin cooperation
