### ISSUE TITLE
Currently no IBM Power(ppc64le) based image is available in kubearbitrator public repository

### ISSUE THREAD

**Issue by damora** [kubernetes-retired/kube-batch#241]
Installing kube-arbitrator on an IBM Power(ppc64le)  cluster using the helm install instructions outlined in the tutorial results in x86 image being pulled from public repository. Ultimately, the container fails with an exec format error. It would be useful to provide a image for IBM Power servers. Perhaps we can use manifest list to make sure the right images get pulled for x86 or Power(ppc64le) or ARM, etc.

**Comment by k82cn** [comment]
Yes, it's reasonable to provide ppc64le image as part of release :)
