### ISSUE TITLE
Add RestartPolicy to QueueJob controller

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#271]
Currently, the QueueJob controller is similar to RC controller that restart pod if failed/deleted; that meet the requirement of Spark, but can not support TF training and MPI. So the proposal is to introduce "RestartPolicy" to QueueJob to support different framework.

**Comment by etiennecoutaud** [comment]
I can work on it if nobody does !

**Comment by k82cn** [comment]
@etiennecoutaud , nobody works on this right now, thanks very much for your contribution :)

**Comment by k82cn** [comment]
@etiennecoutaud , how about the design doc ? I think we can make is "simple" in recent release :)

**Comment by etiennecoutaud** [comment]
We can iterate on this : https://docs.google.com/document/d/11-9GqpXovVqCxaF_avCD8ptyFy66l1Jy913Zo7ksrCI/edit?usp=sharing

**Comment by k82cn** [comment]
@etiennecoutaud , really sorry for the delay; during the discussion of Coscheduling/Gang-scheduling, we're going to support PodGroup's lifecycle instead of QueueJob, but the major logic/concept are similar. Will you continue the work? If not, I'm going to refresh your design doc to continue the work :)

**Comment by k82cn** [comment]
xref https://github.com/kubernetes-sigs/kube-batch/issues/388

**Comment by k82cn** [comment]
I'm going to close this one; will trace all stuff at #388 :)
