### ISSUE TITLE
schedulerName specified per QueueJob instead of per Pod Template

### ISSUE THREAD

**Issue by scostache** [kubernetes-retired/kube-batch#285]
Currently the scheduler name is specified as part of the pod template. When creating a QueueJob with multiple pod "groups" (pods created from different templates), making the user to specify the scheduler name for each template might be error prone. Can we have it as part of the QueueJob template and then filled-in automatically in each pod template?

**Comment by k82cn** [comment]
That's reasonable to me: if no schedulerName in pod template, set it to QueueJob's; otherwise, keep it as is.

**Comment by scostache** [comment]
PR #293

**Comment by k82cn** [comment]
Fixed by  #293
