### ISSUE TITLE
Enable LeaderElect for both scheduler and controller

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#299]
Currently, both `kar-scheduler` and `kar-controllers` did not have LeaderElect that makes unexpected behavior if started multiple components.

**Comment by k82cn** [comment]
The `kar-scheduler` part is for release-0.1; `kar-controller` is under discussion :)

**Comment by wackxu** [comment]
I want to help fix this, do you have started @k82cn? I have finished it.

**Comment by k82cn** [comment]
@wackxu , that's great, thanks very much :) I'll review it ASAP :)
