### ISSUE TITLE
kube-batchd can not aware of the changes of gpu resources when scale up cluster.

### ISSUE THREAD

**Issue by GarnettWang** [kubernetes-retired/kube-batch#302]
**Is this a BUG REPORT or FEATURE REQUEST?:**

- /kind bug

**What happened:**

- step 1: Enable kubelfow/tf-operator's `--enable-gang-scheduler` flag.
- step2: Create a TFJob object and assigned its' schedulerName to kube-batchd. The Pods belong to this TFJob object has configed with more request gpus then the available gpus in the cluster. So, these Pods will be pending.
- step3: I add some gpu servers to the cluster, make the available gpus is enough. These pending pods should be running right now after the nodes added successfully, but they still be pending.

**How to reproduce it (as minimally and precisely as possible):**

**Anything else we need to know?:**

- Restart kube-batchd can make the behave normally, the pending pods will be scheduled and running.
- kube-batchd  behaves normally with cpu and memory when scale up cluster. 

**Environment:**

- kubernetes 1.10.4
- kube-arbitrator release-0.1
- tf-operator v0.2.0-rc1

**Comment by GarnettWang** [comment]
after add `--logtostderr --v 4` flag to kube-batchd，I make sure the gpu number of node's Idle filed in schedulercache has not be detected successfully.

```
idle(cpu 6900.00, memory 61588021248.00, GPU 0) used(cpu 1100.00, memory 524288000.00, GPU 0) allocatable(cpu 8000.00, memory 62112309248.00, GPU 1) pods(4)
```

the new node's Idle gpu number should be `GPU 1`(equal to allocatable GPU number), but it's zero.

after restart kube-batchd, the Idle filed is ok.

**Comment by k82cn** [comment]
Sync up offline, the major reason is GPU maybe updated later after adding node :). We also missed this case in master. I'll upmerge the PR when it's ready :)
