### ISSUE TITLE
Does kube-arbitrator support pod affinity?

### ISSUE THREAD

**Issue by cheyang** [kubernetes-retired/kube-batch#337]
I'm using kube-arbitrator. I'm wondering if it supports pod affinity?

**Comment by k82cn** [comment]
nop, it only support node affinity right now; but I will open a PR to support pod affinity, as we're going to reuse pod affinity from upstream.

**Comment by cheyang** [comment]
Thanks, will you also support release v0.1?

**Comment by k82cn** [comment]
@cheyang , are you still using 0.1? it's in product or test env?

**Comment by cheyang** [comment]
I'm using it with TFJob. Can master version support TFJob?

**Comment by k82cn** [comment]
yes, we support it with the latest version.

**Comment by k82cn** [comment]
I need some time for this feature, as pod affinity need go through all pod by zone which is an expensive operations.

**Comment by gaocegege** [comment]
FYI, We are working on a doc about how to integrate tfjob with kube-arbitrator: https://github.com/kubeflow/tf-operator/issues/743

Thanks for your awesome work and we are looking forward to this feature!

/cc @ChanYiLin

**Comment by chenyangxueHDU** [comment]
Looking forward to this feature!
