### ISSUE TITLE
Support MPI job by kube-batch

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#351]
For now, we support several feature for batch job. And MPI is a typical batch job we need to support. In 0.3, we'd like to get MPI job run by kube-batch.

**Comment by k82cn** [comment]
We should test it with https://www.kubeflow.org/docs/guides/components/mpi/

**Comment by jeefy** [comment]
What are your thoughts on creating another CRD like "mpiJob.scheduling.incubator.k8s.io" which then creates a:
- k8s job with the kube-batch scheduler
- podGroup for the job
- Headless Service that targets all pods for the job
- Network Policy that locks down communication between job-pods (optional/configurable)

The pods themselves have an init container that will `dig` the headless service, grab all the pods, and generate the mpi "hostfile"

From there we should be able to run `mpiexec` successfully.

**Comment by k82cn** [comment]
My original thoughts of this issue is to build such kind of `mpijob`; I'm considering mpi-operator because I may not have enough effort on it :(

If you can contribute, that'll be great :)

**Comment by jeefy** [comment]
I'd love to contribute to this. :) 

Were you looking to re-implement the kube-flow MPI operator or were you looking to start from scratch?

If from scratch, what are your thoughts on my above idea?

**Comment by k82cn** [comment]
I prefer to start it from scratch; similar to your above idea; in additional, we need to provide index to each 'pod/task', and prefer not to use `StatefulSet` which is used for long-running service, IMO.

**Comment by k82cn** [comment]
> I intend on cleaning the code up, then creating a PR into kube-batch, but it works.

That's great ! 

Just go through the code, it seems we use configmap + /etc/hosts; is it possible to use headless service?

**Comment by jeefy** [comment]
I ran into a problem with that: The service endpoints don't populate till the pods are actually in a "running" state. 

With what I've learned so far, it's likely I could probably make headless services work, it'd just be another object that we'd manage.

Thoughts?

**Comment by jeefy** [comment]
Heya @k82cn -- Any further thoughts on this? 

Thanks!

**Comment by k82cn** [comment]
@jeefy , sorry for the delay, I'm testing that. keep you posted later.

**Comment by k82cn** [comment]
/close

kube-batch only focus on scheduling part, so it's out of scope to this repo :)
