### ISSUE TITLE
"Tutorial of kube-arbitrator" display changed

### ISSUE THREAD

**Issue by KeenH** [kubernetes-retired/kube-batch#375]
Tutorial of [kube-arbitrator](https://github.com/kubernetes-incubator/kube-arbitrator/blob/release-0.2/doc/usage/tutorial.md#tutorial-of-kube-arbitrator)

**PLATFORMS e.g. 'uname -a'**:
[Linux xxxx  3.10.0-862.6.3.el7.x86_64 #1 SMP Fri Jun 15 17:57:37 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux ]

**COMMANDS OR DAEMONS**: -- list all related components
[# helm list ]

**DESCRIPTION**: -- symptom of the problem a customer would see
[ 
# helm list
NAME        	REVISION	UPDATED                 	STATUS  	CHART                	NAMESPACE
dozing-otter	1       	Thu Jun 14 18:52:15 2018	DEPLOYED	kube-arbitrator-0.2.0	kube-system

the real output changed.  

]

**IMPACT**: -- impact of problem in customer env (best/worse case scenarios)
[ ]

**EXPECTED BEHAVIOR**:
[ 

NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
plinking-rabbit 1               Mon Sep 10 01:56:07 2018        DEPLOYED        kube-batchd-0.2.0                       kube-system

]

**HOW TO REPRODUCE/DETAILS OF PROBLEM**: -- full details of the problem
[ ]

**Comment by k82cn** [comment]
NAP; the name of release is random generated by helm.
