### ISSUE TITLE
Rename kube-arbitrator to kube-batch in code

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#389]
**FOUND IN VERSION** (Details about the version, e.g. 0.7. Please list the other versions which this bug exist.)
master

**PLATFORMS e.g. 'uname -a'**:
all

**COMMANDS OR DAEMONS**: -- list all related components
all

**DESCRIPTION**: -- symptom of the problem a customer would see

As kube-arbitrator was moved to kube-batch, we should update all related code to match that.

**Tasks**:

- [ ] Updates imports
- [ ] Updates CI
- [ ] Updates related docs

**Comment by Atul9** [comment]
@k82cn I would like to work on this.

**Comment by Atul9** [comment]
@k82cn I have opened up a PR for this - #390
