### ISSUE TITLE
Need to config log level and schedule control loop frequency in configure file.

### ISSUE THREAD

**Issue by tizhou86** [kubernetes-retired/kube-batch#412]
When trying to integrate kube-batch with [paddle](http://www.paddlepaddle.org/) operator, the scheduler log is pretty hard to keep track with, need to config log level and schedule control loop frequency in configure file.

**Comment by k82cn** [comment]
The log level can be changed by "-v"'; we're using glog, so we can not control log by file/struct. Opened PR to handle scheduler period :)
