### ISSUE TITLE
Added tutorials for features

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#434]
**DESCRIPTION**: -- symptom of the problem a customer would see

For now, kube-batch supports several features as follow; but we only have basic tutorial and design doc for gang-scheduling. It's better to have related docs for all features.

- [ ] Gang-scheduling/Coscheduling (https://github.com/kubernetes/community/pull/2337)
- [ ] Preemption/Reclaim
- [ ] Task Priority within Job
- [ ] Queue
- [ ] DRF for Job sharing within Queue

**Comment by Jeffwan** [comment]
I can help on this issue and I think that's a great opportunity to learn this project. My plan is to try all these features and then write tutorials.

**Comment by k82cn** [comment]
that's great :) 
I'll remove help-wanted label for you.

**Comment by afortiorama** [comment]
Hi,

I'm trying to understand how kube-batch would work? I assume scheduling based on resources is left to kubernetes scheduler (at least this is what I understand from your kube-batch image. Would you schedule jobs according to priorities and user fairshares like a classic batch system? I'm afraid it is not clear from the documentation. If not (yet?) is it something you are planning?

**Comment by k82cn** [comment]
>  I assume scheduling based on resources is left to kubernetes scheduler

`kube-batch` is another scheduler here; it will make the scheduling decision directly. 

> Would you schedule jobs according to priorities and user fairshares like a classic batch system?

yes, that's what're doing here.

**Comment by afortiorama** [comment]
Another maybe silly question. "DRF for Job sharing within Queue" does it mean you are going to use Django for authentication and authorization on use of resources?

**Comment by afortiorama** [comment]
That's another DRF I guess. But it would be interesting to know if you have any authentication/authorization policy layer.

**Comment by k82cn** [comment]
> DRF 

it's only one of policy, there're some others policy/algorithm here.

>  any authentication/authorization policy layer

It's based on current k8s feature; we did not handle that in scheduler.

**Comment by zoux86** [comment]
Hi,
where to find these detail tutorials and design doc for Queue or gang-scheduling. 
thanks.

**Comment by Jeffwan** [comment]
@zoux86 I think that's the only tutorial now. https://github.com/kubernetes-sigs/kube-batch/blob/master/doc/usage/tutorial.md

Check a real example here. https://github.com/kubeflow/website/blob/master/content/docs/other-guides/job-scheduling.md

Queue part is missing in the tutorial. Let me finish tutorial this week.

**Comment by yylin1** [comment]
@Jeffwan I look forward to seeing your tutorial .
I am following kube-batch on kubeflow in my research.

**Comment by zoux86** [comment]
@Jeffwan is there a documentation about Queue.
Do you know what role the Queue playing in.   #670 
i will be very appreciated if you can help me to solve these confusion.Thanks.

**Comment by Jeffwan** [comment]
@zoux86 sorry I was a little bit busy with some releases this week. Already kick off this task and add more uses cases in the doc.

**Comment by k82cn** [comment]
/reopen

Let's keep this open until we have doc for each feature :)

**Comment by asifdxtreme** [comment]
https://github.com/kubernetes-sigs/kube-batch/pull/703

**Comment by yylin1** [comment]
Hi, In  tutorials  could  add more about the scheduler configuration ?
Such as the plugin configuration and detailed plugin arguments example about the  ConfigMap.
