### ISSUE TITLE
Does kube-batch support soft podAffinity?

### ISSUE THREAD

**Issue by chenyangxueHDU** [kubernetes-retired/kube-batch#448]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
I found soft podAffinity can not work. I checked the code that I found there is only predicates in the kube-batch. In the default scheduler, it has predicates and prioritizing. The soft podAffinity need `interpod_affinity.go` in priorities.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
does not support right now, let me handle that :)

/assign

**Comment by k82cn** [comment]
Got requirements from some users that this is urgent for tf workload; so I changed priority to urgent, and I'll handle it ASAP :)

**Comment by k82cn** [comment]
fixed by #587
