### ISSUE TITLE
[feature] Add support for podGroup number limits for one queue

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes-retired/kube-batch#452]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature
 /kind feature

**What happened**:
For scenarios of BigData and ML, the batch jobs often summited in queues, we need to provide the capacity to control  the number of running pod groups in queues with limited hardware resources.
**What you expected to happen**:
Add a parameter in Queue API:
```
type QueueSpec struct {
	Weight int32 `json:"weight,omitempty" protobuf:"bytes,1,opt,name=weight"`
         //  PodGroupNumber defines the max number of running podGroup in one queue, default to infinite.
        PodGroupNumber `json:"podgroupnumber,omitempty" protobuf:"bytes,1,opt,name=podgroupnumber"`
}
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hex108** [comment]
@k82cn I could start to work on it using admission webhook if you have not started.

**Comment by k82cn** [comment]
/assign hex108

I'm not working on that, please go ahead :)

**Comment by jiaxuanzhou** [comment]
@hex108 it is perfect if you also consider the resource quota of one podGroup queue, default to be infinite.
```
type QueueSpec struct {
	Weight int32 `json:"weight,omitempty" protobuf:"bytes,1,opt,name=weight"`
         //  PodGroupNumber defines the max number of running podGroup in one queue, default to infinite.
        PodGroupNumber `json:"podgroupnumber,omitempty" protobuf:"bytes,1,opt,name=podgroupnumber"`
        ResourceQuota *Resource `json:"resourcequota,omitempty`
}
```

**Comment by hex108** [comment]
@jiaxuanzhou There is no resource quota for `PodGroup`, is there any use case for it?

**Comment by jiaxuanzhou** [comment]
> @jiaxuanzhou There is no resource quota for `PodGroup`, is there any use case for it?
the resource quota is for the queue of the pgs
in prod, the users are teams to run the jobs, but the resources can not be shared fairly even we use the namespace queue
so we can restrict them by claiming the resource limits for the queues in a manual way.

**Comment by hex108** [comment]
@jiaxuanzhou You might need something like `minResource` that mentioned at https://github.com/kubernetes-sigs/kube-batch/issues/813#issuecomment-485305620?

**Comment by jiaxuanzhou** [comment]
@hex108 actually , I need `maxResource` for one queue

**Comment by hex108** [comment]
> @hex108 actually , I need `maxResource` for one queue

Thanks. Get it now! We'll add it. cc @k82cn

**Comment by jiaxuanzhou** [comment]
@hex108 thx, 👍

**Comment by jiaxuanzhou** [comment]
> @hex108 thx, 👍

test

**Comment by k82cn** [comment]
@jiaxuanzhou , what's the purpose of `maxResources`? are you trying to avoid too many pending pods? If so, "delay pod creation" maybe helpful.

**Comment by jiaxuanzhou** [comment]
> @jiaxuanzhou , what's the purpose of `maxResources`? are you trying to avoid too many pending pods? If so, "delay pod creation" maybe helpful.

`maxResource` defines the threshold of the resource for one queue, once the threshold reached, the subsequent  jobs will still stay in pending status even the idle resource of the cluster can satisfy them.

**Comment by k82cn** [comment]
> maxResource defines the threshold of the resource for one queue, once the threshold reached, the subsequent jobs will still stay in pending status even the idle resource of the cluster can satisfy them.

Similar to Quota but for `Job` and `Queue`, right? Admission controller + Queue controller maybe better :)

**Comment by jiaxuanzhou** [comment]
> > maxResource defines the threshold of the resource for one queue, once the threshold reached, the subsequent jobs will still stay in pending status even the idle resource of the cluster can satisfy them.
> 
> Similar to Quota but for `Job` and `Queue`, right? Admission controller + Queue controller maybe better :)

yeah, Quota for queue.
