### ISSUE TITLE
Incorrect schema configuration in kube-batch event recorder

### ISSUE THREAD

**Issue by adam-marek** [kubernetes-retired/kube-batch#469]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
When scheduling PDB based jobs (tf-operator) the following messages appear in kube-batch log:

``
E1107 14:45:49.713897       1 event.go:259] Could not construct reference to: '&v1beta1.PodDisruptionBudget{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"multi-batch", GenerateName:"", Namespace:"piotrek", SelfLink:"/apis/policy/v1beta1/namespaces/piotrek/poddisruptionbudgets/multi-batch", UID:"b70fd9aa-e29b-11e8-91fa-525816070400", ResourceVersion:"15333", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63677198705, loc:(*time.Location)(0x1f4cd40)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference{v1.OwnerReference{APIVersion:"kubeflow.org/v1alpha2", Kind:"TFJob", Name:"multi-batch", UID:"b70dbc36-e29b-11e8-91fa-525816070400", Controller:(*bool)(0xc000588bdb), BlockOwnerDeletion:(*bool)(0xc000588bdc)}}, Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc0004200e0), Selector:(*v1.LabelSelector)(0xc000420100), MaxUnavailable:(*intstr.IntOrString)(nil)}, Status:v1beta1.PodDisruptionBudgetStatus{ObservedGeneration:1, DisruptedPods:map[string]v1.Time(nil), PodDisruptionsAllowed:0, CurrentHealthy:3, DesiredHealthy:4, ExpectedPods:4}}' due to: 'no kind is registered for the type v1beta1.PodDisruptionBudget'. Will not report event: 'Warning' 'Unschedulable' 'not enough valid tasks for gang-scheduling'
``
**What you expected to happen**:
No error messages.
**How to reproduce it (as minimally and precisely as possible)**:
Schedule any PDB based gangs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
I can not remember the PDB version in 1.10 (v1alpha1 or v1beta1). kube-batch build on 1.11, and 1.10 is out of service : https://v1-10.docs.kubernetes.io/docs/search/?q=PodDisruptionBudget

**Comment by adam-marek** [comment]
The proper schema for event targets still needs to be registered with the broadcaster though, to avoid the errors while sending events (currently the scheme only includes scheduling/v1alpha1 entities). Interestingly the events *will* propagate without it, it's just that the errors mentioned will be recorded in the log.

**Comment by k82cn** [comment]
ok, got that.
