### ISSUE TITLE
Generate default queue

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#479]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

In #465 , we introduced `--default-queue` to make sure all jobs are sharing resources within default queue; but user has to create it; it's better to create it automatically by kube-batch/controllers.

**Comment by jiaxuanzhou** [comment]
@k8s2cn， how about adding a validation logic at the moment of start
BTW， would we also consider generating the crd resources of queue and podgroup when kube-batch in flight ?

**Comment by k82cn** [comment]
> @k8s2cn， how about adding a validation logic at the moment of start

em... we also need to handle the case that user created `Queue` before, e.g. `--namespace-as-queue=false`, and created two `Queue`; we do not know whether we should clean them.

> BTW， would we also consider generating the crd resources of queue and podgroup when kube-batch in flight ?

we used to create those CRDs automatically; I removed it because we may update version of API. One option is to only create newest CRDs, and provide an option to disable it if user want to create other version of API.

**Comment by adam-marek** [comment]
One alternative to having the CRDs creation hard-coded in kube-batch would be to a have well-maintained and documented Helm chart (possibly in the official Helm repo)  representing the typical use-cases (HPC, ML, etc.) via its configuration settings.
Alternatively, to make it even more convenient to newcomers, one could think of creating *separate* pre-configured charts for each of the targeted use cases.

**Comment by k82cn** [comment]
> well-maintained and documented Helm chart

That's a good idea !!

**Comment by k82cn** [comment]
Already handled in 0.4.1 :)
