### ISSUE TITLE
Behavior with PreferredDuringSchedulingIgnoredDuringExecution

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes-retired/kube-batch#485]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

Apologies, if its not the correct place to post this.
It's more of a question and not so much a request for a feature.
I have noticed that in the e2e_test that it supports NodeAffinity, but there is a test only for RequiredDuringSchedulingIgnoredDuringExecution.
Would it work without a problem with PreferredDuringSchedulingIgnoredDuringExecution ?
If yes, how would it take into consideration if there is weight specified as an option as well?

Thanks!

**Comment by k82cn** [comment]
xref https://github.com/kubernetes-sigs/kube-batch/issues/448

@YiannisGkoufas , thanks for your interesting :) We did not support priorities right now, I'd like to get it done in 0.3 release :)

Do you have any use case asking for this feature?

**Comment by k82cn** [comment]
fixed by #587
