### ISSUE TITLE
Add performance metrics

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#487]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

It's better to provide performance metrics of kube-batch for user to monitor scheduler's throughput :)

/cc @jiaxuanzhou

**Comment by Jeffwan** [comment]
@k82cn  I'd like to take this feature. Could we just expose some key metrics like default scheduler doing and custom metrics from kube-batch?

**Comment by Jeffwan** [comment]
I was stuck in my work and now I can come back working on this task.
