### ISSUE TITLE
Replace godep with dep

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#528]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Replace godep with dep

**Comment by Jeffwan** [comment]
I am new to golang and it's dependency management tools. Looks like it's a very good first issue for beginners. I'd like to take this one and help to migrate to dep.

**Comment by k82cn** [comment]
great :)

@Jeffwan , seems you're not a member of kubernetes-sigs, I can not assign issue to you; but I'll remove help-wanted label for you :)

**Comment by Jeffwan** [comment]
@k82cn Sound great. Thanks!
