### ISSUE TITLE
Support Equivalence failure cache by template-uuid

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#538]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

For batch workload, there're several "similar" tasks in one job; if one task failed to fit one node, the other tasks will have the same result (except pod affinity/anti-affinity). In kube-batch, we don-t know which tasks are similar, but we can support customized indexed, e.g. an annotation of task template uuid.

**Comment by k82cn** [comment]
xref https://github.com/kubernetes/kubernetes/issues/72322

**Comment by k82cn** [comment]
**NOTE**: the result of pod affinity/ant-affinity can not be re-used, let's handle other predicates in v0.4 .

**Comment by zionwu** [comment]
I would like to work on this issue. Per my understanding, we have to wait for the upstream issue kubernetes/kubernetes#72322 to be fixed, right？ 

And the change will be adding a map to the session.  The map will cache the result that if a template-uuid fits a node.   The map will be used in actions like allocate to improve the performance.

**Comment by k82cn** [comment]
It's not necessary to wait for kubernetes/kubernetes#72322 ; we can have that feature here, and propose it to upstream :)

**Comment by k82cn** [comment]
> And the change will be adding a map to the session. The map will cache the result that if a template-uuid fits a node. The map will be used in actions like allocate to improve the performance.

Yes, we need to add a map in session; and this map is used by `PredicatesFn` directly, we do not need to change any actions :)

**Comment by zionwu** [comment]
> we can have that feature here, and propose it to upstream

So we will calculate the pod-template-hash for the pod.  How do we store the hash?  I can come up with two approaches:
1. Set it as the pod's annotation, and call API to update the pod, maybe in `SchedulerCache.AddPod`. So that we don't have to re-calculate the hash everytime.
2. Add a new field in `TaskInfo`, calculate and set the field in `NewTaskInfo`.  

Which one do you prefer? Or any better approach?

**Comment by k82cn** [comment]
> So we will calculate the pod-template-hash for the pod. How do we store the hash? I can come up with two approaches:

Calculating hash is really heavy, prefer to let operation/controller set an annotation for it. In kube-batch, only the pods from the same PodGroup will check eCache.

**Comment by k82cn** [comment]
And we need to pay attention on pod affinity/anti-affinity.

**Comment by zionwu** [comment]
>  let operation/controller set an annotation for it

Do you mean the controllers in controller manager?
If so then we will have two PR, one for controller manager, another for kube-batch, right?

**Comment by k82cn** [comment]
> If so then we will have two PR, one for controller manager, another for kube-batch, right?

nop, we only support this feature in kube-batch; other operator, e.g. tf-operator, will decide whether use it or not. And user can aslo add annotation in PodTemplate which is not convience.

For the proposal in upstream, I'd suggest to add this annotation into pod template in controller manager.

**Comment by zionwu** [comment]
Ok, got it, thanks.
I will work on the PR and let you review it once it's ready.

**Comment by k82cn** [comment]
@zionwu , thanks very much! Please continue your work :)

**Comment by hex108** [comment]
I think it is a good solution to `Add a new field in TaskInfo, calculate and set the field in NewTaskInfo`. Although `Calculating hash is really heavy`, we only calculates it once when we put it to `TaskInfo`.

**Comment by k82cn** [comment]
regarding "hash", how to resolve conflict?

**Comment by hex108** [comment]
@k82cn In my option the conflict is very rare, even it happens, kubelet could deal with it well.

**Comment by k82cn** [comment]
> kubelet could deal with it well.

if hash conflict, scheduler may not bind pod.

**Comment by hex108** [comment]
> > kubelet could deal with it well.
> 
> if hash conflict, scheduler may not bind pod.

The hash is stored in `TaskInfo`, it is just used for equivalence cache. We do not need to add it to pod.

**Comment by zionwu** [comment]
@k82cn @hex108 Do we have a conclusion on how to get the hash?  do we let controller to set it as annotation or calculate it by kube-batch? 

I also checked the latest [implementation ](https://github.com/kubernetes/kubernetes/pull/72677) of eCache in default scheduler,  it is using the UID of pod's controller as hash :
``` golang
func GetEquivHash(pod *v1.Pod) types.UID {
	ownerReferences := pod.GetOwnerReferences()
	if ownerReferences != nil {
		return ownerReferences[0].UID
	}

	// If pod's UID of controllerRef is nil, return nil.
	return ""
}
```
In my opinion this is also a good approach, even for controller with multiple pod specs, like tf-operator. For TFJob, if one of its pod specs is unschedulable, the whole job is unschedulable and we don't have to schedule other pod spec of this job.

What do you think of this approach?
