### ISSUE TITLE
GitHub Page build failure

### ISSUE THREAD

**Issue by spiffxp** [kubernetes-retired/kube-batch#545]
/kind bug

Can you please fix or turn off GitHub Pages for this repo?

>The page build failed for the `master` branch with the following error:
>
>The symbolic link `/vendor/github.com/prometheus/procfs/fixtures/26231/exe` targets a file which does not exist within your site's repository. For more information, see https://help.github.com/articles/page-build-failed-symlink-does-not-exist-within-your-site-s-repository/.
>
>For information on troubleshooting Jekyll see:
>
>  https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by k82cn** [comment]
@spiffxp , where did you get this error? https://kubernetes-sigs.github.io/kube-batch/ seems work.

**Comment by k82cn** [comment]
Closed the github pages :)
