### ISSUE TITLE
schedulercache need notify controllers when being updated

### ISSUE THREAD

**Issue by hanghliu** [kubernetes-retired/kube-batch#58]
Is this a BUG REPORT or FEATURE REQUEST?: FEATURE REQUEST

The queuejob controller need get notifications when Queue/QueueJob/Pods are being updated.

This could be implemented as a kind of shared informer and lister

/kind feature

**Comment by swiftdiaries** [comment]
@hanghliu Are you working on this? I thought I could implement a PodLister as part of the helper functions for pod_info.go.

**Comment by jinzhejz** [comment]
@swiftdiaries hanghliu added queue/queuejob informer implementation, I think you could implement the pod_info.go part :)

**Comment by swiftdiaries** [comment]
Thank you. 👍
