### ISSUE TITLE
kube-batch tfjob not support mem cpu gpu

### ISSUE THREAD

**Issue by kinglion811** [kubernetes-retired/kube-batch#580]
k8s: v1.11
I deploy tfjob base on tf-operator(kubeflow),and I set cpu mem gpu request and limit like this
![image](https://user-images.githubusercontent.com/6119243/51903452-266bbd00-23f7-11e9-9565-9ddbe2d0cd86.png)

when the worker running, I   describe the node ,the description like this：
![image](https://user-images.githubusercontent.com/6119243/51903490-43a08b80-23f7-11e9-87f6-2b465f2ae7ea.png)

no resource request and limit info

**Comment by kinglion811** [comment]
this is my error，overlook it

**Comment by k82cn** [comment]
/close

I'm going to close this issue; if any comments/questions, please feel free to reopen it or open another one :)
