### ISSUE TITLE
kube-batch 0.4.1 release

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#621]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

- [x] Release Notes (#630)
- [x] Doc updates (#623)

**Comment by k82cn** [comment]
@thandayuthapani , would you help to draft CHANGES for 0.4.1 based on release-0.4 branch?

**Comment by hex108** [comment]
Hi @k82cn , it seems kubesigs/kube-batch:v0.4.1 has not been pushed https://hub.docker.com/r/kubesigs/kube-batch/tags. All docs that reference it will fail.

**Comment by k82cn** [comment]
@hex108 , yes, I'll upload it ASAP; sorry for the confusion :)

**Comment by k82cn** [comment]
Image was uploaded, close this issue :)
