### ISSUE TITLE
Rename PrioritizeFn to NodeOrderFn

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#624]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup

**Description**:

It's hard to distinguish Priority and Prioritize, so prefer to rename `PrioritizeFn` to `NodeOrderFn`, including prioritize plugin.

**Comment by k82cn** [comment]
@thandayuthapani , please also help on this one :)

**Comment by thandayuthapani** [comment]
@k82cn What should the new plugin name for prioritize? Is `NodeOrder` okay to be new plugin name?

**Comment by k82cn** [comment]
> Is NodeOrder okay to be new plugin name?

Yes, NodeOrder seems ok.

**Comment by k82cn** [comment]
Close on behave of #625 .
