### ISSUE TITLE
Add golint check for source code

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#64]
Now there is gofmt check by `hack/update-gofmt.sh`. 

Need to add golint check for source code and refine code according to golint result. Such as, adding a new script as `hack/update-golint.sh` for the check.

- [X] Add golint tools into this repo (#168)
- [ ] Enable golint check, at least policy directory

**Comment by k82cn** [comment]
We also need to get code pass golint check instead of ignoring failure :).

**Comment by k82cn** [comment]
At least policy/plugin related directories :)
