### ISSUE TITLE
docker image size of kube-batch is too big

### ISSUE THREAD

**Issue by asifdxtreme** [kubernetes-retired/kube-batch#641]
Use Alpine image instead of ubuntu:18.04 for building kube-batch docker image, this will reduce the size of docker image considerably  

**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
docker image size is too big
**What you expected to happen**:
docker image should be small <10MB
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hex108** [comment]
Maybe we could use `scratch` or other minimal image as base image? 

cc @k82cn

**Comment by k82cn** [comment]
a minimal image, e.g. alpine, should be enough for this case.
