### ISSUE TITLE
Refine vendor directory

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#65]
Now some code in vendor directory is redundancy and need sync up from github too. Including but not limited to:

- github.com:kubernetes/api.git
- github.com:kubernetes/apiextensions-apiserver.git
- github.com:kubernetes/apimachinery.git
- github.com:kubernetes/apiserver.git
- github.com:kubernetes/client-go.git
- github.com:kubernetes/metrics.git
- github.com:kubernetes/kube-aggregator.git

**Comment by k82cn** [comment]
fixed by https://github.com/kubernetes-incubator/kube-arbitrator/pull/127
