### ISSUE TITLE
PodGroup's Priority vs. Pod's Priority

### ISSUE THREAD

**Issue by dongeunsuh** [kubernetes-retired/kube-batch#653]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind feature

**Description**:
I'm wonder if there is any plan for the policy for PodGroup's Priority vs. Pod's Priority.
In other words, can someone answer the question mark in the table below?

PodGroup Priority | Pod Priority | JobInfo Priority
:--: | :--: | :--:
O | O | ?
O | X | ?
X | O | ?
X | X | ?

**Comment by k82cn** [comment]
Currently, JobInfo's priority is same with PodGroup's priority, and Pod's priority only works within PodGroup, I'm thinking whether we should also accept Pod's priority as global.

**Comment by dongeunsuh** [comment]
Thanks. 

If I understood correctly, in case we "accept Pod's priority as global"
JobInfo's priority would set to the followings?

-when PodGroup's and Pod's priorities exist (with different priority values)=> use Pod's priority as JobInfo's priority
-when only Pod's priority exist => use Pod's priority as JobInfo's priority
-when only PodGroup's priority exist => use PodGroup's priority as JobInfo's priority
-when no priority specified => use default priority as JobInfo's priority

**Comment by k82cn** [comment]
> If I understood correctly, in case we "accept Pod's priority as global" JobInfo's priority would set to the followings?

Not finilized yet
