### ISSUE TITLE
[Question] Is multi-tenant implemented by   Namespace + ResuorceQuota?

### ISSUE THREAD

**Issue by zoux86** [kubernetes-retired/kube-batch#654]
Hi, !
I've been be interested in multi-tenant, so I was wondering if  you can share how to implement multi-tenant an Resource sharing between multi-tenant .Thanks.

**Comment by k82cn** [comment]
The draft idea will use `Queue` + `Namespace`; we'll propose the design later :)

**Comment by zoux86** [comment]
@k82cn Thanks. By the way , is kube-batch support The management of GPU resources now? 
https://github.com/kubernetes-sigs/kube-batch/pull/227

**Comment by k82cn** [comment]
Yes, we support GPU; but only the counting part; there's an issue in the pipeline for topology (https://github.com/kubernetes-sigs/kube-batch/issues/236).

**Comment by zoux86** [comment]
@k82cn Thanks~

**Comment by hex108** [comment]
@k82cn Is there `minResource` for namespace in your plan? `minResource` means that least resource that namespace could get. When the namespace does not need so much resource, it could share it to other namespaces by weight. When it needs these resource, it could preempt them.

**Comment by k82cn** [comment]
> Is there minResource for namespace in your plan?

hm... that should be part of this; but the design is not finilized.

> When the namespace does not need so much resource, it could share it to other namespaces by weight. When it needs these resource, it could preempt them.

There'll be several thresholds there, e.g. how many resource will be reserved, how many resource it can borrow, how many resource it would like to share :)

**Comment by hex108** [comment]
> There'll be several thresholds there, e.g. how many resource will be reserved, how many resource it can borrow, how many resource it would like to share :)

Yes, are `minResource`, `maxResource` and fair share same as Hadoop YARN? That's what we want exactly.

**Comment by k82cn** [comment]
> Yes, are minResource, maxResource and fair share same as Hadoop YARN? That's what we want exactly.

They're similar :)

**Comment by hex108** [comment]
Could we start work on this part now?

**Comment by k82cn** [comment]
I think we can start design doc & discuss right now. we're discussing the scope of this repo; if we can not add lifecycle management part, we have to implement algorithm here and lifecycle management in [volcano](http://github.com/volcano-sh/volcano) :)

**Comment by hzxuzhonghu** [comment]
xref: https://github.com/volcano-sh/volcano/pull/358
