### ISSUE TITLE
[Error] errors occured when install kube-batch

### ISSUE THREAD

**Issue by zoux86** [kubernetes-retired/kube-batch#657]
A error occured When i run kube-batch in my local k8s cluster followed by this guide:
https://github.com/kubernetes-sigs/kube-batch/blob/master/doc/usage/tutorial.md

when i run the command:
" helm install $GOPATH/src/github.com/kubernetes-sigs/kube-batch/deployment/kube-batch --namespace kube-system" 
i meet the error: 
Error: apiVersion "scheduling.incubator.k8s.io/v1alpha1" in kube-batch/templates/default.yaml is not available

i think i should use the correct apiVersion for my k8s cluster. i run these command:
![image](https://user-images.githubusercontent.com/14087435/54815687-81ba7d00-4ccd-11e9-8625-7bf57e3d2044.png)

And i modified the default.yaml with some apiVersion above. it did not work.

SomeOne else had met this problem? can someone give me some advice? 
Thanks!!!

**Environment**:
- Kubernetes version (use `kubectl version`):  V1.13.4
- Kernel (e.g. `uname -a`): ubuntu 16.04
- Install tools: kubeadm
- Others:

**Comment by k82cn** [comment]
which version are you using? I think that's fixed by https://github.com/kubernetes-sigs/kube-batch/pull/631

**Comment by zoux86** [comment]
kube-batch v0.4.1
i used these commod:
docker pull kubesigs/kube-batch:v0.4.1
git clone --branch v0.4.1  https://github.com/kubernetes-sigs/kube-batch

**Comment by k82cn** [comment]
ok, I think we need to cherry pick #631 :) If can not wait next release, maybe you can update deployment/kube-batch/templates/scheduling_v1alpha1_podgroup.yaml according to the PR .

**Comment by zoux86** [comment]
@k82cn i checked the deployment/kube-batch/templates/scheduling_v1alpha1_podgroup.yaml, and the queue.yam。 The file already contains the contents (crd-install).
![image](https://user-images.githubusercontent.com/14087435/54864004-159e4e80-4d8b-11e9-8d87-cfa19dc73e70.png)

**Comment by k82cn** [comment]
@asifdxtreme , would you help to check that?

**Comment by zoux86** [comment]
@k82cn 
I successed install kube-batch v0.2.0 in my local k8s cluster. But  The same error occured when i install the v0.4. 
![image](https://user-images.githubusercontent.com/14087435/54866184-c4eb1d80-4dab-11e9-9895-89edb992fdc1.png)
![image](https://user-images.githubusercontent.com/14087435/54866214-1abfc580-4dac-11e9-838c-cd6ae9980eab.png)


Environment:
Kubernetes version (use kubectl version): V1.8.7
Kernel (e.g. uname -a): ubuntu 16.04
Install tools: kubeadm
helm: 2.9.0
kube-batch V0.2.0 : success
kube-batch V0.4: fail

**Comment by hex108** [comment]
hi @zoux86 , I just tried it and it succeeded. There are some bugs for helm 2.9.0 to support `crd-install` , the latest version of helm(my version is helm 2.13.0) should work. :) Could you please try it?

**Comment by k82cn** [comment]
> I successed install kube-batch v0.2.0 in my local k8s cluster.

We did not have default queue to install for 0.2 , so no such error :)

**Comment by zoux86** [comment]
@k82cn @hex108  Thanks, i have successed in installing the kube-batch:v0.4.1 with the helm 2.13.0.
