### ISSUE TITLE
[Question] Support ignore resource in some namespaces?

### ISSUE THREAD

**Issue by TommyLike** [kubernetes-retired/kube-batch#661]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
[Question] Does kube batch support ignore tackling the resource in specified namespace?

**Comment by hex108** [comment]
Is there any use case for it?

**Comment by TommyLike** [comment]
It's already been coverd by the conformance plugin in kube batch, what I am saying is to ignore the resource in kube-system namespace, so it's already supported. So close it:)
