### ISSUE TITLE
How dominant resource is calculated in DRF plugin?

### ISSUE THREAD

**Issue by hamiBU** [kubernetes-retired/kube-batch#669]
Hello

I 'm wondering how dominant resource is calculated in DRF plugin file? Also, since DRF is a generalization of Max-Min fairness, I could not find any code which implements it. Could you please help me?

Cheers

**Comment by k82cn** [comment]
please refer to https://github.com/kubernetes-sigs/kube-batch/tree/master/pkg/scheduler/plugins/drf

**Comment by hamiBU** [comment]
In the below structure, the dominant resource has been created but it has not been used in the codes.

**Comment by hamiBU** [comment]
type drfAttr struct {
	share            float64
	dominantResource string
	allocated        *api.Resource
}

dominant resource should be calculated based on the working scheme of DRF.

Cheers

**Comment by k82cn** [comment]
oh, it's calculated on the fly in `calculateShare` right now.
