### ISSUE TITLE
[Question]  Some confusion about Queue, podGroup

### ISSUE THREAD

**Issue by zoux86** [kubernetes-retired/kube-batch#670]
To my understanding:
kube-batch scheduled podGroup rather than pod.  
A podGroup  corresponds to A job. They are one-to-one.
A Namespace corresponds to A queue. They are one-to-one too.
A queue is a queue of PodGroup.  
so i think the jobs in same namespace , are in the same queue.

But After runing my example, i'm confused about my above understanding.
Here is my experiment:

(1) first,  i  created a namespace  named "team1"
(2) second, i created a job. here is the yaml
![image](https://user-images.githubusercontent.com/14087435/55070833-0c322080-50c2-11e9-90b0-34e658534aa0.png)
(3) Then,  i run these commands, the results are in the brackets:
kubectl get queue -n team1                           (default queue)
kubectl get queue                                           (default queue)
kubectl get podgroup -n team1                     (No resources found)
kubectl get podgroup                                     (qj-1  [qj-1 is created by me in another job])

(4) i checked the job,  the job was  ran successfully, and completed. 

### Confusion:
(1）it seems to me that , there is only one queue in the cluster. the queue and Namespace are not one-to-one??
(2) when i created a job without "scheduling.k8s.io/group-name" , no Podgroup is created 
automatically. and the job can ran successfully. the job and podgroup are not one-to-one ?? 

### 
so i am confused about the relations between podGroup,job,queue.
can someone help me? Thanks!!! 

**Anything else we need to know?**:
I refered to  some source code，and some doc of v0.3. It seems there are many queues, and each queue has its weight.

![image](https://user-images.githubusercontent.com/14087435/55072578-73ea6a80-50c6-11e9-882c-07c761178e85.png)
![image](https://user-images.githubusercontent.com/14087435/55072600-82388680-50c6-11e9-9c4e-6e49b0123562.png)

**Environment**:
- Kubernetes version (use `kubectl version`):  v13.3
1 master  and 3 workers

- OS (e.g. from /etc/os-release): ubuntu 16.04
- kube-batch: V0.4.1

**Comment by k82cn** [comment]
> A Namespace corresponds to A queue. They are one-to-one too.

That's not true any more; Queue is cluster level.

> (2) when i created a job without "scheduling.k8s.io/group-name" , no Podgroup is created
automatically. and the job can ran successfully. the job and podgroup are not one-to-one ??

I help to create a shadow PodGroup for such kind of pod, so kube-batch can support default objects in upstream, e.g. ReplicaSet.

**Comment by zoux86** [comment]
@k82cn Thank you for your reply!!!  i still have some questions.
### (1) That's not true any more; Queue is cluster level.
can your briefly explain the function of The Queue? And the relations between queue and podgroup of job. 

Because i see the resource code , It seems there are not only one queue, and resources is assigned by queue's weight.
so i am very wonder what role the queue playing in.
![image](https://user-images.githubusercontent.com/14087435/55088561-e8cd9c80-50e6-11e9-8170-26076a0e22dc.png)
### in proportion.go
![image](https://user-images.githubusercontent.com/14087435/55088980-a193db80-50e7-11e9-9f38-1440f727e048.png)


### (2)I help to create a shadow PodGroup for such kind of pod, so kube-batch can support default objects in upstream, e.g. ReplicaSet.

is it means  the job and podgroup are one-to-one . if a job doesn't contains the  "scheduling.k8s.io/group-name"  ,  kube-batch will create a shadow podGroup to schedule it.

**Comment by Jeffwan** [comment]
> can your briefly explain the function of The Queue? And the relations between queue and podgroup of job.
> 
> Because i see the resource code , It seems there are not only one queue, and resources is assigned by queue's weight.

Hi @zoux86  I think you can consider Queue is used in resource management.  This is very useful in multi-tenancy environments to share a large cluster to improve utilization rate.

You already head to right code snippet. If you get two queue for two groups of users. Resource allocation will be adjusted dynamically by the weights and all of them can get some resources correspondingly.  If queueA is idle, the other queueB can also occupy idle resources and release resource if queueA has jobs.  

PodGroup is the job unit kube-batch schedules. The relation with queue is we put PodGroups object into queue and they ware waiting for resources to be scheduled. This is logical concept of kube-batch.

**Comment by zoux86** [comment]
@Jeffwan Thanks for you reply.  
I understood the function of The queue. And i found the relations between job and podgroup is not one-to-one. 

but when I see the source code like allocate.go. it seems that A job is finished by binding its tasks to nodes. where is The podgroup  play its role??

And Still have a question. 
There are a job and a podgroup.
The job's ".spec.completions " is six. The podgroup's "minMember"  is two.
And the job can be specified to the podgroup. 
Finally there are only two pod completed. is there need a check?

**Comment by Jeffwan** [comment]
@zoux86 I think you might confused about Job here? 
There're two type of jobs here.  `Job` inside kube-batch is actually logical collection of PodGroup object and tasks. You can check `JobInfo` type in job_info.go. 

The another Job is v1batch/job from kubernetes native API.

> but when I see the source code like allocate.go. it seems that A job is finished by binding its tasks to nodes. where is The podgroup play its role??

PodGroup is logical group, it controls like when to bind tasks to nodes.  Binding tasks to nodes is actually part of real scheduling logic. For example, in gang schedule, minMumber will affect if task is going to be schedule or waiting for all resource to be ready and then scheduled.



> The job's ".spec.completions " is six. The podgroup's "minMember" is two.

As I said, the first job is kubernetes job, the second `minMember` is concept in kube-batch. They don't have to be same.

**Comment by zoux86** [comment]
@Jeffwan yes!
i thought the kube-batch's job is based on the k8s'job and only adds some other attributes like QueueID. so i I always thought  there is only one type of job( kubernetes job)!!! 

I checked the JobInfo  and TaskInfo in job_info.go.  i still have some questions?
(1)  It seems a Task can be regarded as a pod of a job. Is it right?
(2)  How the k8s's job is translated into the kube-batch's job?

Thanks again! I'm taking too much of your time

**Comment by Jeffwan** [comment]
> (1) It seems a Task can be regarded as a pod of a job. Is it right?

Yes. TaskInfo has pod info and parent job (podGroup) reference. 


> (2) How the k8s's job is translated into the kube-batch's job

Don't try to match k8s job to kube-batch pod group. there's no logical mapping there. Kubernetes Job will create corresponding pods and kube-batch only use pod information here. The bridge is podGroups in pod annotation.

**Comment by zoux86** [comment]
@Jeffwan Thanks
