### ISSUE TITLE
Release 0.4.2

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#672]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

- [x] Update Release notes
- [x] Cherry pick related issues

**Comment by k82cn** [comment]
@asifdxtreme , would you help to give a list of merged PRs after 0.4.1? We'd better to chery pick them and release 0.4.2 for users :)

**Comment by asifdxtreme** [comment]
Here is the list of PR's added in master branch after 0.4.1 release    
  

 Name    | PR ID  | TBD 
 -----|----------| ------- 
 add balanced resource priority | #636 | <ul><li>- [x] </li></ul> 
Take init containers into account when getting pod resource request | #638 | <ul><li>- [x] </li></ul> 
Support Plugin Arguments | #639 | <ul><li>- [x] </li></ul> 
Support Weight for NodeOrder Plugin | #640  | <ul><li>- [x] </li></ul> 
Add event when task is scheduled | #642  | <ul><li>- [x] </li></ul> 
Return err in Allocate if any error occurs | #643  | <ul><li>- [x] </li></ul> 
Fix Typos | #644  | <ul><li>- [x] </li></ul> 
Order task by CreationTimestamp first, then by UID | #645   | <ul><li>- [x] </li></ul> 
Order queue by CreationTimestamp first, then by UID | #645 | <ul><li>- [x] </li></ul> 
Order job by CreationTimestamp first, then by UID | #645 | <ul><li>- [x] </li></ul> 
In allocate, skip adding Job if its queue is not found | #647 | <ul><li>- [x] </li></ul> 
Preempt lowest priority task first | #649 | <ul><li>- [x] </li></ul> 
Return err in functions of session.go if any error occurs | #651 | <ul><li>- [x] </li></ul> 
Change run option SchedulePeriod's type to make it clear | #652  | <ul><li>- [x] </li></ul> 
Do graceful eviction using default policy | #655 | <ul><li>- [x] </li></ul> 
Add hex108 as reviewer | #656 | <ul><li>- [ ] </li></ul> 
Address helm install error in tutorial.md | #658 | <ul><li>- [x] </li></ul> 
Fix sub exception in reclaim and preempt | #660 | <ul><li>- [x] </li></ul> 
Fix wrong caculation for deserved in proportion plugin | #666 | <ul><li>- [x] </li></ul> 
Change base image to alphine to reduce image size | #671 | <ul><li>- [x] </li></ul> 
Do not create PodGroup and Job for task whose scheduler is not kube-batch | #673  | <ul><li>- [x] </li></ul>

**Comment by k82cn** [comment]
please also include this one: https://github.com/kubernetes-sigs/kube-batch/pull/673 :)
