### ISSUE TITLE
Enhancement: multiple strategy of pod selection

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#69]
The policy will terminate pod to release resources if the `Queue` is underused (Used > Allocated). Now the pod is selected randomly. Need support more strategy of pod selection according to some factors, such as

- Running time
- Priority
- Labels

**Comment by elaron** [comment]
In which circumstances a queue which will be in the state of **underused**? How can the _used_ resource greater than _allocated_ resource?

**Comment by jinzhejz** [comment]
kube-arbitrator allocates resources to queues by weight, if there are no enough tasks in a queue, it will cause a queue underused.

Currently, kube-arbitrator will update scheduling result to `ResourceQuota` periodically, which means the allocated resources.
There is a time window between two updates and the user can also create pods in the time window. If the second update is less than the first update, it may cause the used resource greater than the allocated resource.
