### ISSUE TITLE
Support set default value to the configuration

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#695]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, we dependent on YAML's default value for the configuration of plugin, for example , we have to say "disableJobOrder" because YAML's default vaule of bool is false :( 

One solution is to set the member of `PluginConf` to be a pointer and have a setDefaultFunc for default values.

**Comment by hex108** [comment]
What default values need `setDefaultFunc ` set?  Disable them all by default?

**Comment by k82cn** [comment]
> Disable them all by default?

Nop; I'd like to rename `disableJobOrder` to `jobOrder`, and enable them by default. And we need to have one more configuration, named `Cachable`, for eCache to disable pod affinity/anti-affinity.

**Comment by hex108** [comment]
That's great!

**Comment by hex108** [comment]
@k82cn  How about renaming `disableJobOrder` to `enableJobOrder`?

**Comment by k82cn** [comment]
> How about renaming disableJobOrder to enableJobOrder?

that's ok to me :)
