### ISSUE TITLE
Replace NodeOrder with BestNode

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#699]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, we're using similar way with upstream to sort nodes for a task to get the best node; but the sort action is not necessary as we just want to get the best node after predicates. It's better to get best node directly instead of sort, the time complexity will be reduced from `O(nlogn)` to `O(n)`.

**Comment by hex108** [comment]
If the best node doest not fits, we need pick next one, so will it be better to return a `PriorityQueue`?

**Comment by k82cn** [comment]
why best node does not fit after predicates?

**Comment by hex108** [comment]
@k82cn  If I understand correctly, the predicates does not contain resource predicates, so there is some resource compare logic in https://github.com/kubernetes-sigs/kube-batch/blob/master/pkg/scheduler/actions/allocate/allocate.go#L168. Need we enhance the prediates?

Another situation: administrator perhaps does not enable `predicate` plugin.

**Comment by k82cn** [comment]
> Need we enhance the prediates?

yes, refer to https://github.com/kubernetes-sigs/kube-batch/issues/694 .

> Another situation: administrator perhaps does not enable `predicate` plugin.

Yes, but scheduler can not do anything to enhance that even we have a ordered list :)

**Comment by hex108** [comment]
> > Need we enhance the prediates?
> 
> yes, refer to #694 .

Thanks for it!

> > Another situation: administrator perhaps does not enable `predicate` plugin.
> 
> Yes, but scheduler can not do anything to enhance that even we have a ordered list :)

There is resource predicate in https://github.com/kubernetes-sigs/kube-batch/blob/master/pkg/scheduler/actions/allocate/allocate.go#L168. If we fix #694, we could delete those code. However after we add resource predicate in predicates, if there are no nodes satisfying the task, we will try to allocate for next job and we could not pipeline task(it works like reserving resource), big tasks might starve.

**Comment by k82cn** [comment]
> If we fix #694, we could delete those code. 

In resource predicates, we need to check both idel & releasing to avoid duplicated preemption; the logic is necessary here as the action maybe different when using resources.

**Comment by k82cn** [comment]
btw, we only need this in `allocate` action.
