### ISSUE TITLE
Queue job level resources assignment

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#71]
Kube-arbitrator only allocates resources to queue level now. 

However, a queue also can contain multiple queuejobs as design doc and need to support allocate/assign resources to queuejobs.

There may be two ways:
1. Allocate resources to queuejobs directly by policy
2. Assign resources to queuejobs after policy allocates resources to each queue, such as assign resources to queuejobs in `Interface.Assign()`

**Comment by k82cn** [comment]
handled by https://github.com/kubernetes-incubator/kube-arbitrator/issues/76
