### ISSUE TITLE
Enhancement: allocate CPU by decimals

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#72]
Currently, the minimum allocation unit of CPU by kube-arbitrator is `1`. And the used CPU by pods must be an integer to fit kube-arbitrator.

Need to support smaller minimum allocation unit of CPU to make the kube-arbitrator more flexible, such as `1m`(`1=1000m`)

**Comment by k82cn** [comment]
is this finished?

**Comment by jinzhejz** [comment]
not yet, the minimum allocation unit of CPU is still `1`

**Comment by k82cn** [comment]
handled by https://github.com/kubernetes-incubator/kube-arbitrator/issues/76
