### ISSUE TITLE
Keep backward compatibility for priority class

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#724]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**:

In 0.4, we introduced priority feature for job which need higher version of k8s. It's better to have a flag to disable job priority for backward compatibility.

**Comment by k82cn** [comment]
@thandayuthapani , please help on this one :)

**Comment by thandayuthapani** [comment]
@k82cn I hope a fix has been raised for this issue in this PR https://github.com/kubernetes-sigs/kube-batch/pull/725 by jiaxuanzhou

**Comment by k82cn** [comment]
fixed by #725
