### ISSUE TITLE
Enable k8s pow for this repo

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#755]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, we're using travis for CI; it's better to replace it with k8s pow for other commands e.g. `/retest`.

**Comment by k82cn** [comment]
@asifdxtreme , would take this as high priority? I have to restart CI manually for others :(

**Comment by asifdxtreme** [comment]
https://github.com/kubernetes/test-infra/pull/12201  for `make verify` the prow has been enabled, for others I will enable it tonight

**Comment by k82cn** [comment]
is that ready now?

**Comment by asifdxtreme** [comment]
@k82cn I was facing some issue to run kind inside docker, travis gives out of box support for docker in docker service but for prow we need to make a similar docker image and push it to docker hub so that prow can pull and use it, the issue is resolved now, I will raise the PR to test infra

**Comment by k82cn** [comment]
@asifdxtreme , got that, thanks very much :)
