### ISSUE TITLE
Update dockerhub repo in related doc

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#762]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

To keep backward compatibility, prefer to continue to use `kubesigs` repo for all docker images of Volcano. 

BTW, please also retag `kube-batch` with `vk-scheduler` :)

**Comment by TommyLike** [comment]
@asifdxtreme, also, all the image names in helm chart are hardcoded [here](https://github.com/kubernetes-sigs/volcano/blob/master/deployment/volcano/values.yaml#L3)

**Comment by asifdxtreme** [comment]
> BTW, please also retag `kube-batch` with `vk-scheduler` :)

@k82cn Do we need to add vk-scheduler repo and also keep kube-batch ??

**Comment by asifdxtreme** [comment]
![image](https://user-images.githubusercontent.com/9736066/56134803-f28f4500-5fac-11e9-8a60-496e6bc3130b.png)

**Comment by asifdxtreme** [comment]
@k82cn All the docker images has been updated and kube-batch repo has been retagged, for these changes some change in Readme was supposed to made https://github.com/kubernetes-sigs/volcano/pull/778

**Comment by asifdxtreme** [comment]
@k82cn related docker hup repo's has been updated, we can go ahead and close this issue
