### ISSUE TITLE
Consider support multi-containers pod error code handling

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes-retired/kube-batch#776]
Currently, the `LifecyclePolicy.ExitCode` only takes the first container exit code of the pod. 

So if users have multi-containers pod,  it is impossible for them to specify the error handling behavior for each container in a pod.  

I'd suggest to update the `LifecyclePolicy` API. Since `ExitCode ` is just added, I think it is of little risk to do it now.

**Comment by hzxuzhonghu** [comment]
The initial thought

```golang

type LifecyclePolicy struct {
	ExitCode []ExitCode
}

type ExitCode struct {
      containerName string
      code *int32
}
```

**Comment by TommyLike** [comment]
Do we care about any case of the exitCode or we just care about if there are any unsuccessful exitCode among the containers?

**Comment by hzxuzhonghu** [comment]
Honestly,  in normal case i think it is not necessary.  This is a advanced feature,  maybe useful for those jobs that have some dependencies, for example a training job may return code `x` when the model data is unavailable, and return `y` when the data is of invalid format, return `z` when a temporary network connection err, etc.
