### ISSUE TITLE
verify-gencode.sh can not work

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes-retired/kube-batch#788]

**Comment by TommyLike** [comment]
@hzxuzhonghu any detail?

**Comment by hzxuzhonghu** [comment]
You can try to modify a generated files in client, rather than the deepcopy files, and make a commit.
Then `make verify`, it doesn't fail.

**Comment by TommyLike** [comment]
@hzxuzhonghu yeah, the old logic only focus on deepcopy generated files. Try to update the make file with command:
```
verify: generate-code
```
may work as you expected.

**Comment by hzxuzhonghu** [comment]
I think so. BTW, I understand the ` generate-code` covers `deepcopy`, am i right?

**Comment by TommyLike** [comment]
@hzxuzhonghu yeah. thanks!

**Comment by hzxuzhonghu** [comment]
This is fixed by #792
