### ISSUE TITLE
Add an option to accept configmap of schedulerConf

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes-retired/kube-batch#799]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind feature

**What happened**:

**What you expected to happen**:
kube-batch can load the schedulerConf from the specific configMap or the scheduerConf file, just make it easy to use for the end-users.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Jeffwan** [comment]
@yylin1 talks with me and he has same requirement. I can help on this task

**Comment by k82cn** [comment]
/assign Jeffwan  

thanks very much for your help :)

**Comment by Jeffwan** [comment]
@jiaxuanzhou @yylin1  

I'd like to understand more requirements. Right now, there's a `scheduler-conf` option to read from configuration path. Configmap can mount to controller container.  So technically, we can change the way we deploy kube-batch in helm to mount an user-defined configmap and don't need to change kube-batch.

Another case is users want to dynamically change configurations without restarting kube-batch pod, which requires a configmap listener and reload plugins once the target configmap changes. 

Could you leave more comments on the usage?

**Comment by jiaxuanzhou** [comment]
@Jeffwan  it is great if the kube-batch could support the fsnotify of the configurations 😃

**Comment by yylin1** [comment]
@Jeffwan 
According to the operating situation, dynamically change configurations are more suitable. Using Configmap  to reload plugins is better. 

I think it could add more details illustration about `default configuration` to changes actions and plugin combination.  And add more Plugins Configuration usage examples, more help to understand after reading the design documentation.

**Comment by k82cn** [comment]
`fsnotify` seems better; if conf changed, reload it in next scheduling cycle.

**Comment by jiaxuanzhou** [comment]
@Jeffwan any update?
we can also provide one web-hook, then combine the ability of [configmap-reloader ](https://github.com/jimmidyson/configmap-reload)

**Comment by Jeffwan** [comment]
@jiaxuanzhou Sorry for late response. I was busy with some other areas and didn't get a chance to work on it in past few months. I will get some time to make it in next two weeks. Feel free to take it if you get time.
