### ISSUE TITLE
Data Placement, Rack Awareness and Scheduling

### ISSUE THREAD

**Issue by seshuad** [kubernetes-retired/kube-batch#8]
Not sure if this really fits into the goals for this Incubator, if it does not, please feel free to close the issue. 

At some level a BatchJob processing  a large corpus of data should have awareness of data (location, Skew etc)  for efficient scheduling. 

- If there are multiple copies of the data block, the scheduler should be aware of their locations for enhanced scheduling. 
- The scheduling algorithm should have ability to optimize the cost of data access: local disk --> Single Network Hop (within Rack) --> Multiple Network Hops. 
- Intelligence to address Data Skews: Performance of a BatchJob is directly related to the ability to address data skews efficiently. Schedulers should have intelligence to address the stragglers. 

These requirements may be more appropriate for a layer above the scheduler, if so there should be a way to identify how these requirements would translate into changes at the scheduler layer.

**Comment by foxish** [comment]
This seems to me like it could be an application level concern. For example, in Spark/HDFS, the way we dealt with it was to teach Spark to use node-affinity (https://github.com/apache-spark-on-k8s/spark/issues/315). The scheduler respects [affinity/anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature) fields which can be used for expressing different levels of locality. 

cc @davidopp @liyinan926

**Comment by k82cn** [comment]
I'm also thinking it should be handled by application, e.g. Spark; but for other batch job, e.g. MPI, it do not have such kind of framework to handle it. There's a proposal, named `IndexJob`, in k8s, does it make sense to support data aware scheduling for them? for example, after job_1 finished, its output is on local disk and shared disk, and job_2 prefer to use them, if not in local disk, job_2 will get from shared disk. I'd like to keep this open as a potential requirement.

**Comment by davidopp** [comment]
Yeah, I agree this seems like an application-level concern.

That said, for the example @k82cn gave, my understanding of how local PVs will work is that if job_1 and job_2 both reference the same PersistentVolumeClaim, then job_2 will schedule onto the same node as job_1 (assuming other scheduling requirements are satisfied) even if job_2 is not created until after job_1 terminates.

There's some general discussion of data-locality scheduling in kubernetes/features#139

**Comment by k82cn** [comment]
> my understanding of how local PVs will work is that if job_1 and job_2 both reference the same PersistentVolumeClaim, then job_2 will schedule onto the same node as job_1 (assuming other scheduling requirements are satisfied) even if job_2 is not created until after job_1 terminates.

The output of job_1 is preferred, not required :). If job_2 can be scheduled to those host, it can improve the SLA; if not, it's also OK to run :).
