### ISSUE TITLE
Add Configuration for predicate plugin to enable/disable predicates algorithm

### ISSUE THREAD

**Issue by wackxu** [kubernetes-retired/kube-batch#802]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What you expected to happen**:

Add Configuration for predicate plugin to enable/disable predicates algorithm. refer https://github.com/kubernetes-sigs/kube-batch/pull/800#issuecomment-484351251

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by thandayuthapani** [comment]
@k82cn I think we can make use of `Arguments` Field in scheduler config, either to enable certain predicate functions or disable few predicate functions. Which would be better? Asking user to enable few predicates or disable few predicates?

**Comment by hex108** [comment]
How about asking user to enable some predicates? Use default predicates if no predicates.
