### ISSUE TITLE
the job cannot be scheduled

### ISSUE THREAD

**Issue by 17629264166** [kubernetes-retired/kube-batch#803]
I have copied role.yaml to the templates.but the kubectl logs kube-batch-b788fcdf6-ll9l2 -n kube-system has wrong logs,

 Added pod <kube-system/elasticsearch-logging-0> into cache.
----------
 Failed to list *v1beta1.PriorityClass: the server could not find the requested resource (get priorityclasses.scheduling.k8s.io)

the job cannot be scheduled
qj-1-4qnnb                   0/1       Pending   0          8s        <none>         <none>
qj-1-72wgl                   0/1       Pending   0          8s        <none>         <none>
qj-1-9qftz                   0/1       Pending   0          8s        <none>         <none>
qj-1-h99lh                   0/1       Pending   0          8s        <none>         <none>
qj-1-m4g87                   0/1       Pending   0          8s        <none>         <none>
qj-1-n72gz                   0/1       Pending   0          8s        <none>         <none>
 could you help me ? Thank you very much

**Comment by TommyLike** [comment]
Please ensure the CRD ``priorityclasses.scheduling.k8s.io`` do exist.

**Comment by jiaxuanzhou** [comment]
@17629264166 you can use the latest master branch, start `kube-batch` with flag `--priority-class=false`

**Comment by k82cn** [comment]
Created a cherrypick it at https://github.com/kubernetes-sigs/kube-batch/pull/807 :)

**Comment by k82cn** [comment]
@17629264166 #807 was merged, please try release-0.4 branch code which is more stable :)

**Comment by k82cn** [comment]
/close

@17629264166 , please feel free to re-open it if the issue is still there.
