### ISSUE TITLE
some files are repeated in multiple folders

### ISSUE THREAD

**Issue by SrinivasChilveri** [kubernetes-retired/kube-batch#804]
Is this a BUG REPORT or FEATURE REQUEST?:
/kind maintainability / readability

some files are repeated multiple folders as shown below....I am not sure is it intentional or missed to delete  some how...

/kubernetes-sigs/volcano/code-of-conduct.md  
kubernetes-sigs/volcano/CODE_OF_CONDUCT.md

kubernetes-sigs/volcano/config/crds/scheduling_v1alpha1_podgroup.yaml
kubernetes-sigs/volcano/deployment/kube-batch/templates/scheduling_v1alpha1_podgroup.yaml
/kubernetes-sigs/volcano/deployment/volcano/templates/scheduling_v1alpha1_podgroup.yaml

/kubernetes-sigs/volcano/config/kube-batch-conf.yaml
/kubernetes-sigs/volcano/deployment/volcano/config/kube-batch.conf

similarly other files 

![screenshot](https://user-images.githubusercontent.com/9107906/56405713-26a78600-628b-11e9-8797-450ca9c507ea.png)

**Comment by k82cn** [comment]
@TommyLike please help to remove all code related to vk until donated process is done

**Comment by pdgetrf** [comment]
...

**Comment by TommyLike** [comment]
@pdgetrf  sorry for disturbance of your patch, since the intro of volcano jobs is a huge change both on structure and codes, some of your changes would be removed by accident, I will add a pr to fix it.

**Comment by pdgetrf** [comment]
we have an XXL PR pending and was about to rebase with the master and then this happened. What's the plan here? is it a revert? if yes are we going to re-apply it any time soon?

**Comment by k82cn** [comment]
please continue to rebase your code.
