### ISSUE TITLE
Fairshare based on namespace/queue

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#813]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, kube-batch does not consider namespace when sharing resources within/between queues; a namespace with more workload gets more chance to run its workload, it's unfair to the others. It's better to also balance resources sharing between namespaces.

**Comment by hex108** [comment]
It is OK to share resource share between queues(we could create one queue for one namespace), but we need `minResource` to make a promise to how much resource a queue/namespace could get at least.

**Comment by k82cn** [comment]
> we could create one queue for one namespace

it's one cause we need to cover; but prefer not to bind to that case.
