### ISSUE TITLE
Add design document category

### ISSUE THREAD

**Issue by yylin1** [kubernetes-retired/kube-batch#822]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind feature

**What happened**:
Kube-batch design document needs to be reclassified, can help users to read. Folder action, plugin.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
+1

**Comment by yylin1** [comment]
@k82cn BTW, After release volcano-working, not sure  kube-batch document how to distinguish and use it.

**Comment by k82cn** [comment]
some dir struct in my mind:

```
doc/design
  - apps
     jobs ...
  - scheduling
     actions ...
     plugins ...
```

I'm not sure whether we need additional subdir for actions and plugins :)

**Comment by k82cn** [comment]
@yylin1 , we'll not rebase to volcano-working branch according to the feedback from sig-arch & steering :)

**Comment by yylin1** [comment]
@k82cn thanks, hope to complete improve the document & tutorial, about actions and plugins workflow.
