### ISSUE TITLE
[Question] Running task are preemptable?

### ISSUE THREAD

**Issue by TommyLike** [kubernetes-retired/kube-batch#828]
Does this line [code](https://github.com/kubernetes-sigs/kube-batch/blob/5b048be1b1d15fa03e84b6ea722733b7c87205bb/pkg/scheduler/plugins/gang/gang.go#L77) mean the tasks within `MinAvailable=1` are preemptable even through the job only have one task running? What's the background for this?
```
	preemptableFn := func(preemptor *api.TaskInfo, preemptees []*api.TaskInfo) []*api.TaskInfo {
		var victims []*api.TaskInfo

		for _, preemptee := range preemptees {
			job := ssn.Jobs[preemptee.Job]
			occupid := job.ReadyTaskNum()
			preemptable := job.MinAvailable <= occupid-1 || job.MinAvailable == 1 //here

			if !preemptable {
				glog.V(3).Infof("Can not preempt task <%v/%v> because of gang-scheduling",
					preemptee.Namespace, preemptee.Name)
			} else {
				victims = append(victims, preemptee)
			}
		}

		glog.V(3).Infof("Victims from Gang plugins are %+v", victims)

		return victims
	}
```

**Comment by zoux86** [comment]
I also see these code recently. Below are my personal points of view：
I think the kube-batch don't want to evict more than one pod.  
"job.MinAvailable <= occupid-1 " make sure that.
"job.MinAvailable == 1" is just the special case.

**Comment by TommyLike** [comment]
I smell prejudice 😄
