### ISSUE TITLE
Requested resource for each specific resource type 

### ISSUE THREAD

**Issue by hamiBU** [kubernetes-retired/kube-batch#838]
I'm trying to calculate resource request for each specific resource type. I'm trying two different ways to achieve this:

1)

```For _, pod :=range Pods {
initResreq := GetPodResourceRequest(pod)
reqCPU := initResreq.MilliCPU
reqMemory := initResreq.Memory
}
```

2)

```resreqcpu := api.TaskInfo.Resreq.MilliCPU
 resreqmemory:= api.TaskInfo.Resreq.Memory
```
Is it true to do it as the above codes?

**Comment by k82cn** [comment]
yes, initResreq includes the resource from initContainers; and you can go through scalaresource for extend resources in task.
