### ISSUE TITLE
Standardize language on PodGroup/Pod (vs. Job/Task)

### ISSUE THREAD

**Issue by adrienjt** [kubernetes-retired/kube-batch#845]
In multiple places in the code and documentation, the term "Job" is used in place of "PodGroup", and the term "Task" is used in place of "Pod", though not consistently. To avoid confusing users and contributors, the terms should be standardized.

I know that "Job" and "Task" are common appellations in HPC, but kube-batch should probably standardize on the Kubernetes nomenclature, i.e., "PodGroup" and "Pod".

**Comment by TommyLike** [comment]
I guess the reason is partly because of concepts of Job/Task are more closer to the upper business and can stick to `kube-batch`. That means we can utilize different resources to implement them during the development of kube-batch or kubernetes.
