### ISSUE TITLE
Phase of podgroup status looks incorrect

### ISSUE THREAD

**Issue by iambate** [kubernetes-retired/kube-batch#846]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`podgroup.Status.Phase` shows as `Pending` and `podgroup.Status.Running` as `6`

**What you expected to happen**:

`podgroup.Status.Phase` should be `Running`

**How to reproduce it (as minimally and precisely as possible)**:

Install kube-batch 0.4.2 as mentioned in tutorial and run this example: https://github.com/kubernetes-sigs/kube-batch/blob/master/doc/usage/tutorial.md#gang-scheduling

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

```Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by k82cn** [comment]
should be fixed by https://github.com/kubernetes-sigs/kube-batch/pull/850 :)

**Comment by k82cn** [comment]
@iambate , does #850 work for you?

**Comment by xiaogaozi** [comment]
@k82cn May I ask, is there any schedule to release new version?

**Comment by k82cn** [comment]
According to the schedule, we will have a new release at end of this month.

**Comment by iambate** [comment]
Sorry for late reply. The issue is fixed. Test on latest of master. Thanks for quick fix :)
