### ISSUE TITLE
Inaccurate totalResource in proportion plugin

### ISSUE THREAD

**Issue by zionwu** [kubernetes-retired/kube-batch#858]
In proportion plugin,  the totalResource is the sum of Allocatable of all the nodes:
```golang
for _, n := range ssn.Nodes {
	pp.totalResource.Add(n.Allocatable)
}
```
Then totalResource will be divided into the deserved attr of each queue.

However,  in the cluster there are some pods that occupy resources, which should be subtracted from totalResource, since these resources do not belong to any queue.

**Comment by k82cn** [comment]
makes sense to me :)
