### ISSUE TITLE
v0.4 runtime panic 

### ISSUE THREAD

**Issue by kinglion811** [kubernetes-retired/kube-batch#861]
kubernetes version is :1.11
kube-batch version is:v0.5
when I start kube-batch  and schedule tf job，After running for a while ，kube-batch will panic:
panic information is

``` 
Resource is not sufficient to do operation: <cpu 52000.00, memory 261334462464.00, GPU 0.00> sub <cpu 12000.00, memory 60000000000.00, GPU 2000.00> [recovered]
	panic: Resource is not sufficient to do operation: <cpu 52000.00, memory 261334462464.00, GPU 0.00> sub <cpu 12000.00, memory 60000000000.00, GPU 2000.00>
```

Causing panic are：
![image](https://user-images.githubusercontent.com/6119243/58447344-a6502c80-8136-11e9-9bc3-64d9406c4bd1.png)
![image](https://user-images.githubusercontent.com/6119243/58447370-b6680c00-8136-11e9-8989-86f6d0cae420.png)

**Comment by kinglion811** [comment]
@k82cn

**Comment by k82cn** [comment]
We merged https://github.com/kubernetes-sigs/kube-batch/pull/860 few days ago, which maybe helpful :)

**Comment by kinglion811** [comment]
@k82cn  that can not slove my problem,this issue is mainly node's Idle And the main reason is the inconsistent resources of gpu，I merge the code,the problem reappear

**Comment by k82cn** [comment]
Thanks for your confirmation :)
We also meet similar issue this morning; in our cause, device plugin did not report gpu info in time when kubelet restart. We're working on the PR. Is that similar to your scenario, panic when kubelet with device plugin restart?

**Comment by kinglion811** [comment]
@k82cn maybe,I will confirm your information

**Comment by kinglion811** [comment]
@k82cn 
how is the progress of this issue？

**Comment by k82cn** [comment]
@asifdxtreme , would you help to cherry pick https://github.com/volcano-sh/scheduler/pull/26 into kube-batch :)

**Comment by kinglion811** [comment]
Observed a panic: &errors.errorString{s:"Resource is not sufficient to do operation: <cpu 56000.00, memory 270086234112.00, hugepages-1Gi 0.00, hugepages-2Mi 0.00, nvidia.com/gpu 5000.00> sub <cpu 54000.00, memory 268435456000.00, nvidia.com/gpu 8000.00>"} (Resource is not sufficient to do operation: <cpu 56000.00, memory 270086234112.00, hugepages-1Gi 0.00, hugepages-2Mi 0.00, nvidia.com/gpu 5000.00> sub <cpu 54000.00, memory 268435456000.00, nvidia.com/gpu 8000.00>)
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/workspace/src/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/resource_info.go:158
/workspace/src/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/node_info.go:182
/workspace/src/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/cache/event_handlers.go:82
/workspace/src/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/cache/event_handlers.go:93
/workspace/src/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/cache/event_handlers.go:192
/workspace/src/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/cache/cache.go:262
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/client-go/tools/cache/controller.go:195
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/client-go/tools/cache/controller.go:227
:0
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/client-go/tools/cache/shared_informer.go:554
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390
/workspace/src/github.com/kubernetes-sigs/kube-batch/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71


This is mainly caused by gpu lost，
If the gpu plugin reports gpu lost, it will cause the resource view to be inconsistent.

**Comment by kinglion811** [comment]
@k82cn
