### ISSUE TITLE
 use kubernetes default schedule policies

### ISSUE THREAD

**Issue by davidstack** [kubernetes-retired/kube-batch#864]
we know the default scheduler has several schedule policies, for example: CheckNodeConditionPredicate,PodFitsHost, PodToleratesNodeTaints and so on. can kube-batch use this schedule policies? thanks

**Comment by k82cn** [comment]
Yes, we already import those predicate/priority in kube-batch: https://github.com/kubernetes-sigs/kube-batch/blob/master/pkg/scheduler/plugins/predicates/predicates.go ; if any other requirements, please let me know :)

**Comment by davidstack** [comment]
@k82cn  thks, i only find predicate policy, is there any method for adding priority schedule policy?

**Comment by k82cn** [comment]
please find priorities here: https://github.com/kubernetes-sigs/kube-batch/blob/master/pkg/scheduler/plugins/nodeorder/nodeorder.go :) If any new requirements, please let me know :)

**Comment by davidstack** [comment]
got it,thank you very much
