### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#867]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Let's have a new release for new feature and bug fixes.

**Comment by k82cn** [comment]
btw, we need to get https://github.com/kubernetes-sigs/kube-batch/issues/866 done before new release.

**Comment by asifdxtreme** [comment]
> btw, we need to get #866 done before new release.

#866 has been completed with PR's https://github.com/kubernetes-sigs/kube-batch/pull/871 https://github.com/kubernetes-sigs/kube-batch/pull/870
@k82cn Can we go ahead with the release now??

**Comment by k82cn** [comment]
Yes, I think it's ok to have a new release :)

**Comment by asifdxtreme** [comment]
> Yes, I think it's ok to have a new release :)

@k82cn please create a new release-0.5 branch for the release, currently I don't have permissions to create a new branch.

**Comment by k82cn** [comment]
Done.

**Comment by k82cn** [comment]
@asifdxtreme , when can we get this done?

**Comment by asifdxtreme** [comment]
> @asifdxtreme , when can we get this done?

By today end of the day it will be done
