### ISSUE TITLE
Dual Scheduler，pod should be reschedule

### ISSUE THREAD

**Issue by kinglion811** [kubernetes-retired/kube-batch#868]
There are two schedulers in my kubernetes cluster. My tensorflow job uses kube-batch, but kubelet reports bugs during use:
```
Predicate failed on Pod: worker-0(df3f0bac-987c-11e9-93ec-246e9688fc94), for reason: Node didn't have enough resource: memory, requested: 25769803776, used: 246928233984, capacity: 270086221824
```
The main reason is the inconsistency of resource view and resource conflict between two schedulers.
Can we use the podGroup controller to reschedule the pod that failed to start?
  @k82cn

**Comment by k82cn** [comment]
/assign 

Sure, please let me check that :)
