### ISSUE TITLE
master and worker start in order in a job

### ISSUE THREAD

**Issue by zlcnju** [kubernetes-retired/kube-batch#872]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**Description**:

I have a batch job that the worker pods shouldn't be schedulered until the master pod is in the running state. Is there any solution in kube-batch?

**Comment by k82cn** [comment]
For now, kube-batch support scheduling master pod firstly before worker pods, refer to https://github.com/volcano-sh/volcano/tree/master/docs/samples/kubecon-2019-china/task-priority . After scheduling, it dependent on kubelet to start them; it's better to have a retry in worker pod to wait master pod ready.

BTW, running does not mean master pod is ready to provide service to worker pod, as it dependent on logic in the process/container :)

**Comment by zlcnju** [comment]
> For now, kube-batch support scheduling master pod firstly before worker pods, refer to https://github.com/volcano-sh/volcano/tree/master/docs/samples/kubecon-2019-china/task-priority . After scheduling, it dependent on kubelet to start them; it's better to have a retry in worker pod to wait master pod ready.
> 
> BTW, running does not mean master pod is ready to provide service to worker pod, as it dependent on logic in the process/container :)

If the priority is the schedule order,  it doesn't solve the problem.   Is it a good idea if i add an init container in the worker to check the master is ready to provide service?

**Comment by k82cn** [comment]
> If the priority is the schedule order, it doesn't solve the problem.

It's still necessary to make sure master pod get resources firstly :)

>  Is it a good idea if i add an init container in the worker to check the master is ready to provide service?

That should be ok.
