### ISSUE TITLE
the snapshot of cache may be inconformity with the real cluster resource?

### ISSUE THREAD

**Issue by davidstack** [kubernetes-retired/kube-batch#876]
in a schedule period, kube-batch will snapshot the cache
`snapshot := cache.Snapshot()`
we know the kubelet will update node status every 10 second (the default value),so in the next schedule period ,kube-batch may use old cache? is there any method to avoid this problem? thanks

**Comment by k82cn** [comment]
>  is there any method to avoid this problem? thanks

Not, in a distributed system, we need to make the system also work correctly when status out of sync. kube-batch will make scheduling decision based on the snapshot, if any issue because of node new status, it'll correct it in next scheduling cycle.

**Comment by davidstack** [comment]
ok. got it , but when kube-batch schedule  pod1 to node1, the allocatable resource on  node1 may be  less than pod 1request , the pod will not createed on node1, will kube-batch reschedule pod1 ? or, just depend on the k8s default evicit mechanism?

**Comment by k82cn** [comment]
> the allocatable resource on node1 may be less than pod 1request

It may happen when there's some hardware error, scheduler will make sure it'll not exceed allocatable resources. And if it happened in some cases, the kubelet will reject the pod so kube-batch will re-schedule it.

**Comment by davidstack** [comment]
thanks
