### ISSUE TITLE
Explicit resources allocation

### ISSUE THREAD

**Issue by ocherfas** [kubernetes-retired/kube-batch#878]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**Description**:
Allocate explicit resources to a queue (instead of allocating weights)

I would like to be able to define queues like this for example:

Name: Sample queue
Number of GPUs: 4
CPUs: 20
Memory: 4G 

**Anything else we need to know?**:

**Comment by k82cn** [comment]
@ocherfas , that's the max or min resources of the queue?

**Comment by ocherfas** [comment]
@k82cn  This is the deserved resources of the queue

**Comment by hzxuzhonghu** [comment]
https://github.com/kubernetes-sigs/kube-batch/blob/60060fd95abcbc4656d9733b8c10a313f07b6f17/pkg/apis/scheduling/v1alpha2/types.go#L196-L200

Currently, queue has `Weight` indicate a relative resource limit. And `Capability` indicates the maximum resources the queue can occupy.

I think it is reasonable to have an optional deserved resources field, which should be mutually exclusive with existing fields.
