### ISSUE TITLE
will queue share change in one scheduling priod?

### ISSUE THREAD

**Issue by davidstack** [kubernetes-retired/kube-batch#885]
in allocate action, it will sort queue by the queue by the share of queue. the queues in memory like this arrary:
queue1(share=1)  
queue1(share=1)  
queue3(share=2)  
queue3(share=2)  
queue2(share=3)  
queue2(share=3)  
queue2(share=3)

this sort will not change in this    scheduling priod, because the calculation of share only in the plugin proportion? so allocate will allocate queue one by one? thanks

**Comment by k82cn** [comment]
In each schedule cycle, we'll handle all queues so that's ok.

**Comment by davidstack** [comment]
@k82cn  if cluster has not enough resource, should we schedule one job in one queue, then another job in other queue?

**Comment by k82cn** [comment]
it's not necessary, we already have deserved resources of queue.

**Comment by davidstack** [comment]
ok, thanks
