### ISSUE TITLE
pod will stuck in pending status when host down

### ISSUE THREAD

**Issue by davidstack** [kubernetes-retired/kube-batch#891]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
pod stuck in pending status after bind to the host which is powered off
**What you expected to happen**:
pod will rescheduled when host is down
**How to reproduce it (as minimally and precisely as possible)**:
because of the cluster snapshot, host status will not update immediately,so pod may be binded to a host which is powered off in this schedule period. but kube-batch will update this pod in Binding status. but actually, the pod is in pending status

**Anything else we need to know?**:
i think kube-batch should one goroutine to check this status ,and change the status of pod from binding to pennding in kube-batch cache. 
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
Will GC delete the pod to trigger re-scheduling?

**Comment by davidstack** [comment]
the node has been poweroff，kubelet can not gc ?
