### ISSUE TITLE
Preempt tasks with lower priority

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-retired/kube-batch#894]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

You should be able to configure `kube-batch`, so it preempts tasks of lower priority jobs when higher priority job arrives. Based on the code I read and what I observed on the cluster it looks like there is no way to enforce that. It looks like only `gang`, `drf` and `conformance` provide "preemptable functions". 

Possible solution is to add preemptable function to `priority` plugin:

```go
preemptableFn := func(preemptor *api.TaskInfo, preemptees []*api.TaskInfo) []*api.TaskInfo {
	preemptorJob := ssn.Jobs[preemptor.Job]
	var victims []*api.TaskInfo
	for _, preemptee := range preemptees {
		preempteeJob := ssn.Jobs[preemptee.Job]
		if preempteeJob.Priority >= preemptorJob.Priority {
			glog.V(3).Infof("Can not preempt task <%v/%v> because "+
				"preemptee has greater or equal job priority (%d) than preemptor (%d)",
				preemptee.Namespace, preemptee.Name, preempteeJob.Priority, preemptorJob.Priority)
		} else {
			victims = append(victims, preemptee)
		}
	}
	glog.V(3).Infof("Victims from Priority plugins are %+v", victims)
	return victims
}
ssn.AddPreemptableFn(pp.Name(), preemptableFn)
```

Let me know if this make sense.

**Comment by k82cn** [comment]
yes, that makes sense to me :)
