### ISSUE TITLE
How to leverage kube-batch via python SDK

### ISSUE THREAD

**Issue by Cherishty** [kubernetes-retired/kube-batch#898]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
I am a newcomer in k8s CRD (but familiar with k8s itself), can anyone tell me how to leverage kube-batch via python SDK, which means: 
`how to use python SDK to perform action like kubectl create/delete on podgroup?`

I check the k8s native sdk and the tutorial but don't find the useful interface/guidance

**Comment by k82cn** [comment]
hm... we need to ask k8s python-client on how to generate CRD client. kube-batch will use this python client :)

**Comment by Cherishty** [comment]
Hi @k82cn 
Sorry but I may confuse on your answer, do you mean that currently we have **NO** approach to leverage kube-batch (CRUD pod group) via **python client lib**, only kubectl CLI is available? 

If so, how can other projects (like kubeflow) leverage kube-batch?

**Comment by Cherishty** [comment]
Oppps, I just find 
[kubernetes.client.CustomObjectsApi](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#kubernetesclientcustomobjectsapi) which should work!
May you give some sample for this, in kube-batch usage?

**Comment by k82cn** [comment]
ok, sure; we'll introduce some doc for it :)

**Comment by Cherishty** [comment]
Thanks :)
