### ISSUE TITLE
[Question] How to create Job with different pod spec?

### ISSUE THREAD

**Issue by qw2208** [kubernetes-retired/kube-batch#899]
> /kind feature

**What happened**:
Following the tutorial, I'm wondering how a batch job can set different pod configs? For example, for Parameter Server in a distributed TF job, I don't need GPU resources while worker requires.

Is there any example YAML file for a job with different pod resources?

**Comment by k82cn** [comment]
kube-batch is only a scheduler; the pod's configuration is set by pod's controller, for example, tf-operator or [Volcano](https://github.com/volcano-sh/volcano/blob/master/example/integrations/tensorflow/dist-mnist/tf-dist-mnist-example.yaml)

**Comment by qw2208** [comment]
So is there a way to affiliate different "self-defined" pod to one pod-group via something like annotation?

**Comment by Cherishty** [comment]
I have the same question. That is： 
I have defined several pods (with different images and pv) `separately`, and assign their **annotation** as the **pod-group**. Can I use this way to leverage the gang-scheduling mechanism of kube-batch?

**Comment by k82cn** [comment]
Yes, just make sure those Pods using the same podgroup :)

**Comment by qw2208** [comment]
Let me clarify it:
If I need to create a distributed tensorflow task, I can define several pods **instead of** job and assign their annotation as the pod-group.

**Comment by k82cn** [comment]
yes
