### ISSUE TITLE
Pod group with none events

### ISSUE THREAD

**Issue by qw2208** [kubernetes-retired/kube-batch#901]
> /kind bug

**What happened**:
I was trying to create the job and podgroup as job-01.yaml in [tutorial](https://github.com/kubernetes-sigs/kube-batch/blob/master/doc/usage/tutorial.md) suggests.
However, when I tried to get podgroup, got <none> events which seems odd:
![image](https://user-images.githubusercontent.com/24438413/68119871-d4843480-ff3e-11e9-8162-834a4f8e4814.png)
All the pods are actually pending unexpectedly:
![image](https://user-images.githubusercontent.com/24438413/68119930-f8477a80-ff3e-11e9-9156-73e680bb3a56.png)
Those pods are also giving the none events if `kubectl describe pod`

**Environment**:
- OS (e.g. from /etc/os-release): Centos
- Install tools:
![image](https://user-images.githubusercontent.com/24438413/68119997-2cbb3680-ff3f-11e9-94dc-774888feb461.png)

**Comment by k82cn** [comment]
which version are you using?

**Comment by qw2208** [comment]
Version of what? kube-batch I think is kube-batch-0.4.2. API version is v1alpha1.
![image](https://user-images.githubusercontent.com/24438413/68172760-b4db2380-ffb3-11e9-9d35-a3a5661b4ecc.png)

**Comment by qw2208** [comment]
And kubectl version is 1.14.3 as follows;
![image](https://user-images.githubusercontent.com/24438413/68174973-a7756780-ffba-11e9-906d-dd2883664d7b.png)

**Comment by qw2208** [comment]
![image](https://user-images.githubusercontent.com/24438413/68189337-0b615580-ffe6-11e9-82b0-cbfe8674b38b.png)
Seems something related with configs. No sure how to resolve.

**Comment by k82cn** [comment]
> Seems something related with configs. No sure how to resolve.

Seems permission related.

**Comment by qw2208** [comment]
Yes, I closed it since I resolved it by copying the role.yaml. Thanks.
