### ISSUE TITLE
[Question] Why don't we move `example/role.yaml` to `deployment/kube-batch/templates`

### ISSUE THREAD

**Issue by edwardstudy** [kubernetes-retired/kube-batch#902]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
It failed to list resources at the cluster scope due to permissions.

**What you expected to happen**:
Add `role.yaml` kube-batch needed to helm deployment.

**How to reproduce it (as minimally and precisely as possible)**:
Following tutorial.md

**Anything else we need to know?**:
None
**Environment**:
None

**Comment by k82cn** [comment]
`role.yaml` gives more permission than its needed; we did not take time to enhance that :)
That's ok to me to move it with "right" permission :)
