### ISSUE TITLE
Allow to specify min batch size for shadow group using annotation

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-retired/kube-batch#904]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**Feature Proposal**

If `scheduling.k8s.io/group-name` is unspecified and `scheduling.k8s.io/group-min-member` is specified then create shadow pod group with min batch size derived from the annotation `scheduling.k8s.io/group-min-member`.

If `scheduling.k8s.io/group-name` is already specified, then `scheduling.k8s.io/group-min-member` will be ignored.

**Why?**

Requiring users to learn new custom resource `PodGroup` and properly handling clean up of such resource is nontrivial and time consuming. In common use case user just want create a batch of pods that will be allocated together at the same time. Extending shadow pod group capabilities could be a solution for this.

**Implementation**

It should be fairly simple few lines change in `createShadowPodGroup()` in `pkg/scheduler/cache/util.go`.

Happy to make a PR.

**Comment by k82cn** [comment]
that's ok to me :)

**Comment by mateuszlitwin** [comment]
Closed in #908
