### ISSUE TITLE
Derive PriorityClassName for shadow pod group from pod PriorityClassName

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-retired/kube-batch#905]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**Implementation**

It should be fairly simple few lines change in `createShadowPodGroup()` in `pkg/scheduler/cache/util.go`

Happy to make a PR.

**Comment by k82cn** [comment]
that makes sense to me :)

BTW, did you try Volcano: http://github.com/volcano-sh/volcano ?

**Comment by mateuszlitwin** [comment]
@k82cn Hi! I looked it up. Volcano seems like a more complicated solution. There are more custom resource definitions to learn and services to maintain. I want batch scheduling capabilities without forcing users to use specific frameworks or workflows, ideally enabling batch scheduling should be as simple specifying scheduler name plus some optional annotations in the pod template or controller.

**Comment by k82cn** [comment]
oh, Volcano provide the same interface for scheduling part; it's up to you whether using job or not. One more feature is `Queue`, whose lifecycle is managed by queue controller :)
