### ISSUE TITLE
Roadmap: Using QueueQuota and QueueJobQuota to replace ResourceQuota

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#91]
Currently, ResourceQuota is used to limit resource usage of each queue(namespace level indeed).

In the roadmap, we need to new admission control for Queue and QueueJob to limit resource usage.
* QueueQuota: resource usage limitation of a Queue
* QueueQuotaController: admission controller for QueueQuota
* QueueJobQuota: resource usage limitation of a QueueJob
* QueueJobQuotaController: admission controller for QueueJobQuota

**Comment by pineking** [comment]
@k82cn , I have talked with @jinzhejz offline, 
that's a great feature, do we have the release date of this roadmap?
