### ISSUE TITLE
[Question] How kube batch ensure the cache consistency if when another pod is scheduled by the default kube scheduler?

### ISSUE THREAD

**Issue by qw2208** [kubernetes-retired/kube-batch#922]
/kind feature

Since kube batch session open and seems that it will update its cache snapshot every 1 second (pls correct me if I didn't understand correctly), what if there are any other normal pod being scheduled by the k8s default scheduler during this time period of 1s and will the kube-batch cache still be consistent with the cluster status?

Or will kube-batch and kube-scheduler schedule pods at the same time?

Thanks in advance if there are some explanation or code reference could work as well.

**Comment by k82cn** [comment]
If kube-batch and default-scheduler scheduled pods to the same pods, kubelet will reject it if no more resources, and ether kube-batch or default-scheduler will re-schedule it later :)

**Comment by qw2208** [comment]
Thanks @k82cn for your reply. What if in a period of 1s, other tasks of a podgroup are scheduled but one task is rejected by the kubelet, then the gang scheduling might fail?

**Comment by xial-thu** [comment]
my understanding is that gang scheduling will fail. it's not a big deal.  we still have the next round. asynchronous binding in default scheduler may fail too and default scheduler will add that pod to backoffQ or unschedulableQ and waits for the next chance to re-schedule. if you really mind the race condition, scheduling framework proposed at community, aiming at extending the abilities of default scheduler by plugins may help. Mr @k82cn is one of the proposers. Codes are already merged in k8s.

**Comment by qw2208** [comment]
All right. I'm just trying to estimate the risk of leveraging this plugin as the batch scheduler.
So,
1. In a large cluster, it still seems all right to co-exist the kube-scheduler as the default scheduler and kube-batch for gang scheduling?
2. Could you pls give me some reference on the extension of default scheduler?

**Comment by xial-thu** [comment]
1. It depends on your scenario because resource race condition exists. Things get out of control if both schedulers are busy in a resource-limited environment. I apply and only apply kube-batch/volcano to AI jobs so CPU/memory does not bother me.
2. https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md

**Comment by qw2208** [comment]
Thanks @xial-thu for your reply.

1. Is there any side effect if all normal pods are scheduled by kube-batch?
2. For normal pods, my understanding is that if for a normal pod whose scheduler_name is kube-batch and even if we don't have a podgroup for this pod, the kube-batch will create a shadow podgroup and schedule it?

**Comment by xial-thu** [comment]
> Thanks @xial-thu for your reply.
> 
> 1. Is there any side effect if all normal pods are scheduled by kube-batch?
> 2. For normal pods, my understanding is that if for a normal pod whose scheduler_name is kube-batch and even if we don't have a podgroup for this pod, the kube-batch will create a shadow podgroup and schedule it?

pods are associated with podgroup only by annotations. normal pods will be scheduled anyway. logics are in the codes.
kube-batch re-uses `predicate` and `prioritize` so all the algorithms are available. I will suggest testing the stability of kube-batch itself at first. Besides, the re-schedule mechanism between kube-batch and default-scheduler is kind of different. I cannot give the exact answer because my team hacks a lot based on kube-batch. But sometimes it crashes.

**Comment by qw2208** [comment]
Haa, it seems that kube batch can be still a feasible option for gang scheduling but not that ready.

**Comment by k82cn** [comment]
I think you can try [volcano](http://github.com/volcano-sh/volcano) which we already put into product environment :)

**Comment by qw2208** [comment]
Two questions then:
1. If we use volcano, all the pods should be scheduled by volcano?
2. Will kube batch be able to support large-scale scenarios maybe someday? Is it still updating?

**Comment by k82cn** [comment]
> 1. If we use volcano, all the pods should be scheduled by volcano?

It's up to you; it support multi-scheduler way, and it also support features in default scheduler.

> 2. Will kube batch be able to support large-scale scenarios maybe someday? Is it still updating?

It dependent on how define "large-scale scenarios", it's still updating.

**Comment by k82cn** [comment]
> I cannot give the exact answer because my team hacks a lot based on kube-batch. But sometimes it crashes.

@xial-thu , any detail on that?

**Comment by xial-thu** [comment]
> @xial-thu , any detail on that?

Sorry I lost the screen snapshot and logs. I remember pods are shown as something like “admissionError”, I'm not sure.

I'm planning to do some benchmark by kubemark. I'll update if I met that problem again.

**Comment by k82cn** [comment]
> I'm planning to do some benchmark by kubemark. I'll update if I met that problem again.

That's great !
