### ISSUE TITLE
Inconsistent release tag names

### ISSUE THREAD

**Issue by terrytangyuan** [kubernetes-retired/kube-batch#929]
I found this when debugging https://github.com/kubeflow/mpi-operator/pull/169. The most recent release https://github.com/kubernetes-sigs/kube-batch/releases/tag/0.5.0 should be named v0.5.0 instead of 0.5.0 to be consistent with previous releases. 
cc: @k82cn

**Comment by k82cn** [comment]
oh, good catch! Let me correct that :)

**Comment by terrytangyuan** [comment]
Perhaps keep 0.5.0 and then just create another tag v0.5.0 from the same commit just in case anyone is already using the existing 0.5.0 tag.

**Comment by terrytangyuan** [comment]
@k82cn Any update on this? Could you create a new tag v0.5.0? I believe the existing tag is having issue with many dependency management systems - they cannot detect this correctly.

**Comment by k82cn** [comment]
ok, I'll update it today :)

**Comment by k82cn** [comment]
done :) xref https://github.com/kubernetes-sigs/kube-batch/tree/v0.5.0

**Comment by terrytangyuan** [comment]
Thanks!
