### ISSUE TITLE
performance concern about kube-batch

### ISSUE THREAD

**Issue by xial-thu** [kubernetes-retired/kube-batch#930]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature
/kind testing

**What happened**:
I've done a benchmark of kube-batch on a local kubemark cluster with 200 hollow nodes. I'm using [perf-tests/clusterloader2](https://github.com/kubernetes/perf-tests) with default density-test-config.

Results are not satisfying. Throughput of kube-batch is 4.99 pod/s on average, which is relatively low compared to default scheduler(20 pod/s). The pod start-up latency is about 
```bash
    {
      "data": {
        "Perc50": 33655.356,
        "Perc90": 65417.187,
        "Perc99": 74992.761
      },
      "unit": "ms",
      "labels": {
        "Metric": "pod_startup"
      }
```
which does not meet the demand of kubernetes SLO standard (99% 5s)

So what I'm concerned about is the performance of kube-batch.

**What you expected to happen**:

I'm expecting explanation about the performance problem. I guess it's the same with volcano. 

I'm wondering where is the bottleneck?

**How to reproduce it (as minimally and precisely as possible)**:
1. build a kubemark cluster
2. do some benchmark with clusterloader2

**Anything else we need to know?**:

I'm using kube-batch v0.4

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos 
- Kernel (e.g. `uname -a`): 3.10
- Install tools:
- Others:

**Comment by k82cn** [comment]
did you try volcano? Someone did performance improve in Volcano but did not merge it back.
