### ISSUE TITLE
Cut a release with Kubernetes 1.16 dependency

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes-retired/kube-batch#939]
**What happened**:

We need a release with Kubernetes 1.16 dependency. 

**What you expected to happen**:

I am using v0.4.2 at this moment. When I migrate to Kubernetes 1.16. we see this error. 
```
../../../../pkg/mod/github.com/kubernetes-sigs/kube-batch@v0.0.0-20190101025100-b0dbd4f2df59/pkg/client/clientset/versioned/typed/scheduling/v1alpha1/scheduling_client.go:79:32: undefined: serializer.DirectCodecFactory
```
`serializer.DirectCodecFactory` was deleted in 1.16 and we need to use `serializer.WithoutConversionCodecFactory` or https://github.com/kubernetes-sigs/kube-batch/blob/2e934d1c88604d01dcb5c40ff9f0534875a10730/pkg/client/clientset/versioned/typed/scheduling/v1alpha1/scheduling_client.go#L78. 

The reason we use 1.16 is volcano now uses 1.16.x. When I migrate to volcano, v1 implementation can be changed to volcano which depends on 1.16.x. while v1beta1 still uses kube-batch with < 1.16 kubernetes. In order to make build work, we hope to get a kube-batch version with 1.16 Kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
v0.5.0 doesn't have latest dependency as well. 

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Jeffwan** [comment]
Let's hold this. Trying to resolve all the dependency problems by `replacing` kubernetes to a compatible version. This is kind of painful.

**Comment by k82cn** [comment]
ok, if there's anything I can do, please let me know :)

**Comment by zw0610** [comment]
Is it possible to replace `serializer.DirectCodecFactory` with `serializer.WithoutConversionCodecFactory` in a future Kube-batch release? 

Since I have to stick to apimachinery 0.16.x (or any versions after Kubernetes 1.15), my solution is to put a hack script, which adding `type DirectCodecFactory WithoutConversionCodecFactory` to the `vendor/k8s.io/apimachinery/pkg/runtime/serializer/codec_factory.go`.

**Comment by k82cn** [comment]
> Is it possible to replace `serializer.DirectCodecFactory` with `serializer.WithoutConversionCodecFactory` in a future Kube-batch release?
> 
> Since I have to stick to apimachinery 0.16.x (or any versions after Kubernetes 1.15), my solution is to put a hack script, which adding `type DirectCodecFactory WithoutConversionCodecFactory` to the `vendor/k8s.io/apimachinery/pkg/runtime/serializer/codec_factory.go`.

Would you try Volcano ?

**Comment by zw0610** [comment]
> > Is it possible to replace `serializer.DirectCodecFactory` with `serializer.WithoutConversionCodecFactory` in a future Kube-batch release?
> > Since I have to stick to apimachinery 0.16.x (or any versions after Kubernetes 1.15), my solution is to put a hack script, which adding `type DirectCodecFactory WithoutConversionCodecFactory` to the `vendor/k8s.io/apimachinery/pkg/runtime/serializer/codec_factory.go`.
> 
> Would you try Volcano ?

Sure.
