### ISSUE TITLE
Status of kube-batch

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-retired/kube-batch#948]
Per requirement from the Kubernetes steering committee, we'd like to make the latest status of each sub-project clearly documented to the public.

@k82cn I suppose volcano is the successor of kube-batch, and hence kube-batch is no longer actively maintained. So should we either document the status in README, or as you requested earlier, make kube-batch archived?

**Comment by k82cn** [comment]
I'm going to update README, and then let's archived this repo :)

**Comment by Huang-Wei** [comment]
> I'm going to update README, and then let's archived this repo :)

Thanks Klaus!

**Comment by Huang-Wei** [comment]
/reopen

@k82cn any plan on maintaining the health/activeness of this project?

**Comment by k82cn** [comment]
> @k82cn any plan on maintaining the health/activeness of this project?

@Huang-Wei , please feel free to archive this one, I put more time on other project, e.g. https://github.com/xflops/flame .

**Comment by kerthcet** [comment]
Hi I hope to put some efforts to this project, can you defer the archive. Or I can help to maintain this project, I'm currently working on the batch workloads and hope to make it works smoothly with the kubernetes, especially with the kube-scheduler.

**Comment by kerthcet** [comment]
By the way, I'm a reviewer of kubernetes sig scheduling, and a developer of volcano, also I work on the batch wg to contribute ideas and solutions to the upstream, e.g. kueue(a kubernetes native job queueing system), I hope kubernetes can support the batch scenarios smoothly.

**Comment by Huang-Wei** [comment]
@kerthcet i may prefer to star a new subproject if needed. This repo's codebase may beed big revamp to catch up with latest k8s version, which IMO may not worth the efforts.

**Comment by kerthcet** [comment]
Thanks @Huang-Wei I'll reconsider your suggestion about sponsoring a new project.

**Comment by k82cn** [comment]
> . This repo's codebase may beed big revamp to catch up with latest k8s version, which IMO may not worth the efforts.

The codebase is not bound to k8s version, it'll not take much effort to bump up the version.

@kerthcet , why not contribute to Volcano? And would you share your use case for kube-batch?

**Comment by kerthcet** [comment]
Volcano is an excellent project, our company is exploring it right now, so I'm also contributing to it. But it has its own ecosystem, it has its own job api, job queueing system, but we're now supporting it upstream, although not as mature as volcano right now. I hope we can have a batch system collaborating with the upstream smoothly, under the k/sig is a good approach.

My case is mostly about  GPU sharing and network-architecture aware or stuff like that.

**Comment by Huang-Wei** [comment]
> The codebase is not bound to k8s version

it does actually: https://github.com/kubernetes-sigs/kube-batch/blob/b3fc2cd0cfe5293c61c19a1134c1ea9eb526f22f/go.mod#L19-L25

**Comment by k82cn** [comment]
> But it has its own ecosystem, it has its own job api, job queueing system, but we're now supporting it upstream, although not as mature as volcano right now. I hope we can have a batch system collaborating with the upstream smoothly, under the k/sig is a good approach.

The Volcano can also support customized jobs, including the job in upstream. For queueing system, kube-batch and volcano are similar; as both of them are built on my experience/understanding on LSF/Slurm (also integrate some ideas on cloud native), which is a bit different with k8s.

For the collaboration, both k8s/batch-wg and CNCF/batch-wg are the good place to discussion requirements.

**Comment by kerthcet** [comment]
Exactly, thanks @k82cn for all your efforts.

**Comment by lowang-bh** [comment]
I have developed kube-batch  base on this codebase, because there are still old k8s version in used. I would like to submit those fixed issues.

**Comment by mrbobbytables** [comment]
Repo is to be archived, for more information please see: https://github.com/kubernetes/org/issues/4200

/close
