### ISSUE TITLE
how to deploy kube-batch on arm64

### ISSUE THREAD

**Issue by magnate3** [kubernetes-retired/kube-batch#952]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
root@ubuntu:~# helm install ~/kube-batch/deployment/kube-batch   --namespace kube-system  --generate-name 
NAME: kube-batch-1625472656
LAST DEPLOYED: Mon Jul  5 16:10:56 2021
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The batch scheduler of Kubernetes.
root@ubuntu:~# kubectl logs kube-batch-7bfddfb67c-9l8pw   -n kube-system
**standard_init_linux.go:228: exec user process caused: exec format error**
root@ubuntu:~# 
root@ubuntu:~# kubectl get pods --all-namespaces -o wide | grep kube-batch
kube-system      kube-batch-7bfddfb67c-9l8pw                **0/1     Error       3          57s     10.244.29.10     bogon     <none>           <none>**
root@ubuntu:~# 

root@ubuntu:~# kubectl describe pods kube-batch-7bfddfb67c-9l8pw   -n kube-system
Name:         kube-batch-7bfddfb67c-9l8pw
Namespace:    kube-system
Priority:     0
Node:         bogon/10.10.16.81
Start Time:   Mon, 05 Jul 2021 16:11:00 +0800
Labels:       app=kube-batch
              pod-template-hash=7bfddfb67c
Annotations:  cni.projectcalico.org/podIP: 10.244.29.10/32
              cni.projectcalico.org/podIPs: 10.244.29.10/32
Status:       Running
IP:           10.244.29.10
IPs:
  IP:           10.244.29.10
Controlled By:  ReplicaSet/kube-batch-7bfddfb67c
Containers:
  kube-batch:
    Container ID:  docker://25062fd9fa1f32fab79bb09653802239105dbb76f3d05381088ed8073fbec0af
    Image:         kubesigs/kube-batch:v0.5
    Image ID:      docker-pullable://kubesigs/kube-batch@sha256:4e4c2ebf19a341fd450efdd5d4cffd1addb5abbc7163fd9b08f7f7b1bc42e0ab
    Port:          <none>
    Host Port:     <none>
    Args:
      --logtostderr
      --v
      3
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 05 Jul 2021 16:12:38 +0800
      Finished:     Mon, 05 Jul 2021 16:12:38 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 05 Jul 2021 16:11:44 +0800
      Finished:     Mon, 05 Jul 2021 16:11:44 +0800
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:        2
      memory:     2Gi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5w25p (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-5w25p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5w25p
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  <unknown>          default-scheduler  Successfully assigned kube-system/kube-batch-7bfddfb67c-9l8pw to bogon
  Normal   Pulled     9s (x5 over 104s)  kubelet, bogon     Container image "kubesigs/kube-batch:v0.5" already present on machine
  Normal   Created    9s (x5 over 104s)  kubelet, bogon     Created container kube-batch
  Normal   Started    9s (x5 over 104s)  kubelet, bogon     Started container kube-batch
  Warning  BackOff    8s (x9 over 102s)  kubelet, bogon     Back-off restarting failed container
root@ubuntu:~# 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
 

root@ubuntu:~# uname -a
Linux ubuntu 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:10:24 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
root@ubuntu:~# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:36:32Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
root@ubuntu:~#

**Comment by sftim** [comment]
/retitle how to deploy kube-batch on arm64
