### ISSUE TITLE
How to create the task using the Queue?

### ISSUE THREAD

**Issue by pineking** [kubernetes-retired/kube-batch#97]
I found document for how to create the queue and set the resource quota:

https://github.com/kubernetes-incubator/kube-arbitrator/blob/master/doc/usage/tutorial.md

But could anyone tell me how to create the pod/task into the queue?

**Comment by k82cn** [comment]
En, @jinzhejz is working on the example on how to create it. Currently, it need user to set/update resource request of the Queue; there's also a backlog on ResourceEstimation of Queue's request for default kind, e.g. RC, deployment.

**Comment by pineking** [comment]
@k82cn @jinzhejz Thanks for the reply. I will have a try.
